{
  "hash": "60d87a991253fbc99e903a7b13b5c160",
  "result": {
    "engine": "knitr",
    "markdown": "# 静态模型 {#sec-staticmodel}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## 简介\n\n在本书中，我们将重点讨论相对简单的种群模型，但也将开始为理解更复杂模型的某些要求做准备。我们所说的 “更复杂 ”是指通常用于模拟捕捞种群动态的年龄结构模型。然而，我们可以利用这些更复杂模型的组成部分来说明我们可以称之为 “静态模型 ”的数据拟合。静态模型用于描述个体生长过程的方程形式、成熟度如何随年龄或体型变化、补充与成熟或产卵生物量之间的 “种群-补充 ”关系，以及渔具对被捕捞种群的选择性。这种静态模型显示了相关变量（年龄长度、成熟年龄或长度等）之间的函数关系，而且这些关系被赋予了一个相当大的假设，即随着时间的推移保持不变。\n\n这种静态模型与我们所说的动态模型形成对比，动态模型试图描述诸如资源量变化之类的过程，其中估算的值是早期资源量的函数。这样的动态模型总是包含一个自我参考的元素，可能还有其他驱动因素，所有这些都有助于我们试图描述或建模的动态。\n\n在某些情况下，如果假定静态或稳定的过程发生了明显的变化，这些本应是静态的关系可能会被 “时间阻断”，这意味着假定这些关系在两个不同的时间段之间以阶梯状的方式发生变化。实际上，如果这些过程发生了变化，很可能是在一段时期内比较平稳地发生了变化，但遗憾的是，拥有足够的数据来很好地描述这种渐进的变化通常是不可能的。\n\n我们首先用这类模型来实现更多的例子，因为正如我们在第 [-@sec-paraestimat] 章 “[模型参数估计](04-application.qmd)（*Model Parameter Estimation*）”中所看到的，这些静态模型往往比具有足够灵活性来描述动态过程的模型更容易实现。\n\n## 生产力参数\n\n顾名思义，所有的生物种群都是由个体集合而成的，因此会表现出一些新出现的特性，这些特性部分地概括了这些种群的特性。鉴于目前正在发生的许多物种灭绝事件，我同意，一个物种中的少数甚至单个个体可能会构成 “种群（population） ”的某种限制，但我们将只关注更丰富的种群，而撇开这些可悲的极端情况。在这里，我们将重点关注个体的生长、成熟和补充，所有这些都与种群的生产力有关。与生长快、成熟早、繁殖力高的物种相比，生长慢、成熟晚、繁殖力低的物种的生产力往往较低，尽管其潜在稳定性更高。生命史特征的进化是一个复杂而又引人入胜的课题，我建议大家对其进行研究 [@beverton1993a; @stearns1977; @stearns1992]。不过，在这里我们将重点讨论简单得多的模型。即便如此，在对捕捞种群进行建模时，了解相关物种的生命史特征可能产生的影响，对于解释观察到的动态变化还是很有帮助的。不要忘记，生物过程建模极大地受益于生物知识和理解。\n\n## 生长\n\n忽略任何潜在的迁入和迁出，种群生产力是种群中新个体的补充和种群中已有个体的生长的综合结果。这些都是积极因素，而自然死亡率以及捕捞种群中的捕捞死亡率等消极因素则抵消了这些积极因素。个体生长的重要性是渔业生态学中有大量关于个体生长的文献的原因之一（Summerfelt 和 Hall，1987）。尽管我刚才写到，如果要建立模型，了解生物过程非常重要，但其中大部分文献都与生长生物学有关，我们将忽略这些文献。相反，我们将专注于个体生长的数学描述。重点在于描述，这一点很重要，因为有些人似乎过于偏爱特定的生长模型，而这些模型仅仅描述了生长过程，并没有真正解释生长过程。\n\n在第 [-@sec-paraestimat] 章 “[模型参数估算](04-application.qmd)”中，我们已经介绍了可用于描述年龄-长度的三种候选模型 （von Bertalanffy、Gompertz 和 Michaelis-Menton），因此我们不再重新讨论这些模型。相反，我们将考虑描述生长的另外两个方面。在年龄-长度方面，我们将研究与季节性生长模型有关的观点，尽管这些观点在淡水系统中很重要，但往往用处有限。更常用的是，我们还将研究如何从标记数据中估计个体生长情况。\n\n在本章中，我们将主要讨论 von Bertalanffy 生长曲线以及使用函数 `vB()` 对其进行的拓展：\n\n$$\nL_t = L_{\\infty} \\left(1 - e^{-K(t - t_0)} \\right ) \n$$ {#eq-5_1}\n\n### 季节性生长曲线\n\n生长速度是一个复杂的过程，不仅受每种动物的体长或年龄的影响，还受环境条件的影响。因此，在温带和极地地区，全年温度变化很大，生长率也会随季节变化。这可以表现为鱼类耳骨（耳石）和其他坚硬部位的确切生长环，它们源于一年中新陈代谢的变化。当然，还有其他因素和事件带来的复杂性和不确定性（例如，硬壳中的假环），但在此我们还是要把重点放在对数据的描述上，假定在分析之前已经解决了这些复杂性（实际情况往往与此不同，不要低估收集有效渔业数据的难度！）。\n\n不同的季节性生长模型已很多，但在此我们将使用 @pitcher1973 提出的一个模型，对 von Bertalanffy 生长曲线进行了修改，在生长率项中加入了正弦波，试图将周期性水温作为生长率的驱动因素，使生长率在冬季减慢，在夏季加快。\n\n$$\n{L}_{t}={{L}_{\\infty }}\\left( 1-{{e}^{-\\left[ C\\sin \\left( \\frac{2\\pi \\left( t-s \\right)}{52} \\right)+K(t-{{t}_{0}} \\right]}} \\right) \n$$ {#eq-5_2}\n\n其中 $L_{\\infty}$ 、$K$ 和 $t_0$ 是 von Bertalanffy 参数，$t$ 是长度 $L_t$ 的周龄， $C$ 决定了围绕非季节性增长曲线的振荡幅度，$s$ 是正弦波在年份中的起点，使用常数 52 反映了使用周作为年内时间步长的单位。如果我们使用月或日作为取样事件之间的时间单位，那么我们将分别使用 12 或 365。我们可以使用 @pitcher1973 对英国淡水鲦鱼（*Phoxinus phoxinus*；虽然鲦鱼的数据是从他们的图中读取的，因此只是近似正确，但足以说明问题）研究的数据。\n\n首先，我们可以绘制现有数据并拟合一条标准的非季节性 von Bertalanffy 生长曲线。拟合曲线使用的是正态随机误差而非对数正态误差，因此我们使用了 `negNLL()` 函数。使用 `ssq()` 函数也是可行的，但由于我们对预测曲线的变化特别感兴趣，因此下文将继续使用 `negNLL()`。如果我们忽略季节性趋势，那么预计曲线周围的变化（由 *sigma* 参数描述）将相对较大。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #vB growth curve fit to Pitcher and Macdonald derived seasonal data  \ndata(minnow); week <- minnow$week; length <- minnow$length  \npars <- c(75,0.1,-10.0,3.5); label=c(\"Linf\",\"K\",\"t0\",\"sigma\")  \nbestvB <- nlm(f=negNLL,p=pars,funk=vB,ages=week,observed=length,  \n              typsize=magnitude(pars))  \npredL <- vB(bestvB$estimate,0:160)  \noutfit(bestvB,backtran = FALSE,title=\"Non-Seasonal vB\",parnames=label)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnlm solution:  Non-Seasonal vB \nminimum     :  150.6117 \niterations  :  41 \ncode        :  3 Either ~local min or steptol too small \n                par      gradient\nLinf   89.447640823  5.878821e-05\nK       0.009909338  2.705709e-01\nt0    -16.337065207 -4.717809e-05\nsigma   3.741419172  2.711355e-04\n```\n\n\n:::\n:::\n\n\n\n根据季节性数据拟合的标准 von Bertalanffy 曲线 [@eq-5_1] ，其 *sigma* 参数约为 $3.7$，这只是反映了一个事实，即数据围绕平均增长曲线摆动，因此残差会相对较大。如果我们使用季节性调整曲线，这种变化会大大减少，因此我们可以预测 *sigma* 应该小得多。为了拟合季节性增长曲线，我们需要定义一个反映新模型结构的修改后 `vB()` 函数 [@eq-5_2]。当然，在拟合任何新模型时，第一步必然是需要一个函数来根据一组参数生成预测值。我们可以将负对数似然的计算包含在这个新函数中，但将预测长度的生成保留在一个单独的函数中可以增加我们代码的灵活性。因此，我们将坚持分别使用预测函数和负对数似然计算函数的策略。在参数向量 *pars* 中，我们还需要包含 @eq-5_2 中 $C$ 和 $s$ 的初始估计值。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #plot the non-seasonal fit and its residuals.  Figure 5.1  \nparset(plots=c(2,1),margin=c(0.35,0.45,0.02,0.05))   \nplot1(week,length,type=\"p\",cex=1.0,col=2,xlab=\"Weeks\",pch=16,  \n      ylab=\"Length (mm)\",defpar=FALSE)  \nlines(0:160,predL,lwd=2,col=1)  \n # calculate and plot the residuals  \nresids <- length - vB(bestvB$estimate,week)  \nplot1(week,resids,type=\"l\",col=\"darkgrey\",cex=0.9,lwd=2,  \n    xlab=\"Weeks\",lty=3,ylab=\"Normal Residuals\",defpar=FALSE)  \npoints(week,resids,pch=16,cex=1.1,col=\"red\")  \nabline(h=0,col=1,lwd=1)  \n```\n\n::: {.cell-output-display}\n![年龄长度数据来自 Pitcher 和 Macdonald（1973 年），与最佳拟合的 von Bertalanffy 曲线相比，\n显示出生长率的强烈季节性波动。下图中的正态随机残差的季节性模式非常明显，并随着年龄的增长而减小。](05-staticModel_files/figure-pdf/fig-5-1-1.pdf){#fig-5-1 fig-pos='H'}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n # Fit seasonal vB curve, parameters = Linf, K, t0, C, s, sigma  \nsvb <- function(p,ages,inc=52) {  \n  return(p[1]*(1 - exp(-(p[4] * sin(2*pi*(ages - p[5])/inc) +   \n                           p[2] * (ages - p[3])))))  \n} # end of svB  \nspars <- c(bestvB$estimate[1:3],0.1,5,2.0)  # keep sigma at end  \nbestsvb <- nlm(f=negNLL,p=spars,funk=svb,ages=week,observed=length,  \n              typsize=magnitude(spars))   \npredLs <- svb(bestsvb$estimate,0:160)  \noutfit(bestsvb,backtran = FALSE,title=\"Seasonal Growth\",  \n       parnames=c(\"Linf\",\"K\",\"t0\",\"C\",\"s\",\"sigma\"))  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnlm solution:  Seasonal Growth \nminimum     :  105.2252 \niterations  :  21 \ncode        :  2 >1 iterates in tolerance, probably solution \n               par      gradient\nLinf   89.06448059  7.259920e-05\nK       0.01040808  3.973383e-01\nt0    -13.46176841 -5.575919e-05\nC       0.10816263 -5.358897e-03\ns       6.96964772  2.208197e-05\nsigma   1.63926525  7.775261e-05\n```\n\n\n:::\n:::\n\n\n\n增长率的季节性调整对 $L_{\\infty}$ 和 $K$ 值的影响较小，但对 $t_0$ 值的影响较大，因为季节性比标准 `vB()` 函数更能允许最初的快速上升。正如预期的那样，对 *sigma* 参数的影响很大(从 3.74 下降到 1.64 )。模型拟合的改进也很大(增加两个参数的代价是 -veLL 从 150 下降到 105)。如 @fig-5-2 所示，这也反映在整个残差模式的减少及其最大值和最小值的减半上。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #Plot seasonal growth curve and residuals   Figure 5.2  \nparset(plots=c(2,1))  # MQMF utility wrapper function  \nplot1(week,length,type=\"p\",cex=0.9,col=2,xlab=\"Weeks\",pch=16,  \n      ylab=\"Length (mm)\",defpar=FALSE)  \nlines(0:160,predLs,lwd=2,col=1)  \n # calculate and plot the residuals  \nresids <- length - svb(bestsvb$estimate,week)  \nplot1(week,resids,type=\"l\",col=\"darkgrey\",cex=0.9,xlab=\"Weeks\",  \n      lty=3,ylab=\"Normal Residuals\",defpar=FALSE)  \npoints(week,resids,pch=16,cex=1.1,col=\"red\")  \nabline(h=0,col=1,lwd=1)  \n```\n\n::: {.cell-output-display}\n![Pitcher 和 Macdonald（1973）的近似龄长数据与 von Bertalanffy 生长曲线的拟合季节版本。下图是正态随机残差图，残差仍有一系列高于和低于零的运行，但不如非季节性曲线那么有规律。](05-staticModel_files/figure-pdf/fig-5-2-1.pdf){#fig-5-2 fig-pos='H'}\n:::\n:::\n\n\n\n这当然不是唯一可以描述生长率季节性变化的生长曲线，但本节只是对其原理的介绍。事实上，文献中还有很多可供选择的生长曲线，例如甲壳动物的生长曲线，它们是通过蜕皮来增大体型的。因此，严格来说，描述它们的生长需要估算从初始尺寸开始的生长增量，以及它们蜕皮时生长增量的持续时间和频率。不过，在种群层面，如果数量足够多，在种群动力学模型中，连续的生长曲线往往可以充分近似地描述这种生长。\n\n@pitcher1973 对他们的第一条季节性生长曲线所预测的负增长的出现表示反对，但由于他们处理的是从鱼群中选取的样本，并对这些样本的平均值进行拟合，因此没有生物学上的理由可以解释为什么这些样本的平均值在一年中的某些时候不能略有下降。他们还指出，使用直接拟合过程“......在带有交互式图形的 PDP 8-E 计算机上联机需要几个小时：然而，有效的优化方法可以大大缩短时间” [@pitcher1973，第603页]。希望这样的陈述能让读者更加了解现在非线性优化器的易得性、卓越的计算机速度及其分析能力（免费提供的软件，如 R，确实是一种能力）。\n\n### 标记数据的 Fabens 方法\n\n到目前为止，在第[-@sec-paraestimat] 章 “[模型参数估计](04-application.qmd) ”一章和本节的 “静态模型 ”中，我们主要讨论的是年龄-长度数据，这显然需要对样本进行年龄测定和长度测量。遗憾的是，并非所有动物的年龄都能精确到足以使用这种生长描述。在渔业相关科学的早期，一种常用的做法是给鱼类标记、放流（Petersen，1896 ）。回捕鱼类可用于描述其运动特征，后来，通过测量标记时和回捕时的鱼体长度，可用于描述动物的生长情况。在使用标记数据拟合曲线时，需要对用于描述更标准的年龄长度曲线的方程进行转换。因为我们不知道被标记动物的年龄，我们需要一个方程，根据 von Bertalanffy 参数生成预期长度增量，标记时的长度 $L_t$，以及经过时间 $\\Delta t$ 后的长度将是 $L_{t + \\Delta t}$。Fabens(1965) 对 von Bertalanffy 曲线进行了改造，使其可以用于从标记程序中获得的信息(参见本章附录中的完整推导)。通过对一般的 von-Bertalanffy 曲线（ [@eq-5_1]） 的处理，Fabens 得到下面的方程：\n\n$$\n\\begin{split}  \n  & \\Delta \\hat{L}={{L}_{t+\\Delta t}}-{{L}_{t}} \\\\  \n& \\Delta \\hat{L}=\\left( {{L}_{\\infty }}-{{L}_{t}} \\right)\\left( 1-{{e}^{-K\\Delta t}} \\right)  \n\\end{split}  \n$$ {#eq-5_3}\n\n其中，某一动物的初始长度是 $L_t$，$\\Delta L$ 是 $\\Delta t$ 时间段的长度的期望变化。通过使用最小二乘法或负对数似然法，可以估算出 $L_{\\infty}$ 和 $K$ 的值。为了估算 $t_0$值，需要可知年龄的平均长度，因此，通常无法进行 $t_0$ 估计，并且无法确定生长曲线沿年龄轴的确切位置。在这种情况下，$t_0$ 通常被设为 $0$。\n\n如果能够获得至少记录了标记时的初始长度、标记和回捕之间的时间间隔以及在该时间间隔内发生的生长增量的数据，那么我们在给定初始长度和两个参数 $L_{\\infty}$ 和 $K$ 的情况下，建立一个函数，生成所需的预测增长增量，然后利用最大似然，我们就可以获得我们所拥有的任何数据的最佳拟合。\n\n这最好通过绘制一些标记的图来说明 [@fig-5-3] （数据在 **MQMF** 数据集 *blackisland*（鲍鱼种群）中找到）。包括一些较大鲍鱼的零增长。数据云是分散的（噪声），但某种形式的趋势是明显的，生长模型将试图拟合这种趋势。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # tagging growth increment data from Black Island, Tasmania  \ndata(blackisland);  bi <- blackisland # just to keep things brief  \nparset()  \nplot(bi$l1,bi$dl,type=\"p\",pch=16,cex=1.0,col=2,ylim=c(-1,33),  \n     ylab=\"Growth Increment mm\",xlab=\"Initial Length mm\",  \n     panel.first = grid())  \nabline(h=0,col=1)  \n```\n\n::: {.cell-output-display}\n![从塔斯马尼亚州西南角黑岛采集的黑唇鲍鱼标记数据。标记与重捕之间的时间间隔平均为 1.02 年。](05-staticModel_files/figure-pdf/fig-5-3-1.pdf){#fig-5-3 fig-pos='H'}\n:::\n:::\n\n\n\n与第 [-@sec-paraestimat] 章“[模型参数估计](04-application.qmd)”中对生长的描述一样，这里我们将拟合两条生长曲线并与示例标记数据 进行比较。这两条曲线分别是 von Bertalanffy 曲线（Fabens，1965；见 @eq-5_3 ）（鱼类和其它种类的）以及逆 logistic 曲线（Haddon 等，2008 ），更适合难以测定年龄的无脊椎动物所表现出的不确定连续生长。与 von Bertalanffy 曲线相比，逆 logistic 曲线的局限性更大，因为它设计用于以一年为单位的时间增量，或至少是一个恒定的时间增量。\n\n$$\n\\begin{split}  \n  \\Delta L &= \\frac{Max\\Delta L}{1+{{e}^{log(19)({L_t}-L_{50})/\\delta }}} + \\varepsilon \\\\   \n  {L_{t+1}} &= {L_t}+\\Delta L + \\varepsilon   \n\\end{split}  \n$$ {#eq-5_4}\n\n$\\delta$ 等于 $L_{95} - L_{50}$，其中 $L_{50}$ 和 $L_{95}$ 是增长率分别为 $Max \\Delta L$ 的 50% 和 5% 时的长度，$\\varepsilon$ 表示一定长度的平均预期增量的正态随机残差误差。 事后来看，$L_{95}$ 可能定义为 $L_5$ 更好。 请注意，由于进行了 Fabens 变换，Fabens 模型的残差误差与年龄长度模型的残差误差有所不同，尽管二者都使用了正态概率密度函数（稍后详述）。\n\n**MQMF** 中定义了两个函数来生成 von Bertalanffy 曲线的预测生长增量：`fabens()` 和逆 logistic `invl()`。这两个函数的实现非常简单，反映了 @eq-5_3 和 @eq-5_4 。读者应检查这些函数的代码（即不带括号的 `fabens()` 或 `invl()`），并阅读每个函数的帮助。读者很快就会明白，这些函数的定义方式可以方便地使用列名不是 $l1$ 和 $dt$ 的 data.frames。在下文中，我们明确使用了这些名称，尽管我们本可以直接使用默认值。\n\n### 拟合标记数据模型\n\n在模型拟合方面中，我们已经有了生成预测生长增量（ $\\Delta L$ ）所需的函数（`fabens()` 和 `invl()` ）以及优化器 `nlm()`，仍然需要的是在搜索最小值期间计算负对数似然的函数。在这一点上，没有理由使用正态随机误差以外的其他误差。我们将使用 **MQMF** 函数 `negNLL()` 来拟合两条曲线，然后通过可视化和似然比检验对它们进行比较。如果需要更改用于所需数据的列名，可以使用 ....。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # Fit the vB and Inverse Logistic to the tagging data  \nlinm <- lm(bi$dl ~ bi$l1) # simple linear regression  \nparam <- c(170.0,0.3,4.0); label <- c(\"Linf\",\"K\",\"sigma\")  \nmodelvb <- nlm(f=negNLL,p=param,funk=fabens,observed=bi$dl,indat=bi,  \n               initL=\"l1\",delT=\"dt\") # could have used the defaults  \noutfit(modelvb,backtran = FALSE,title=\"vB\",parnames=label)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnlm solution:  vB \nminimum     :  291.1691 \niterations  :  24 \ncode        :  1 gradient close to 0, probably solution \n              par     gradient\nLinf  173.9677972 9.563666e-07\nK       0.2653003 2.656839e-04\nsigma   3.5861240 1.391768e-05\n```\n\n\n:::\n\n```{.r .cell-code}\npredvB <- fabens(modelvb$estimate,bi)  \ncat(\"\\n\")  \n```\n\n```{.r .cell-code}\nparam2 <- c(25.0,130.0,35.0,3.0)   \nlabel2=c(\"MaxDL\",\"L50\",\"delta\",\"sigma\")  \nmodelil <- nlm(f=negNLL,p=param2,funk=invl,observed=bi$dl,indat=bi,  \n               initL=\"l1\",delT=\"dt\")  \noutfit(modelil,backtran = FALSE,title=\"IL\",parnames=label2)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnlm solution:  IL \nminimum     :  277.0122 \niterations  :  26 \ncode        :  1 gradient close to 0, probably solution \n            par      gradient\nMaxDL  21.05654 -2.021972e-06\nL50   130.92643  5.900276e-07\ndelta  40.98771  2.218945e-07\nsigma   3.14555  4.535835e-06\n```\n\n\n:::\n\n```{.r .cell-code}\npredil <- invl(modelil$estimate,bi)  \n```\n:::\n\n\n\n逆 logistic 模型的负对数似然小于 von Bertalanffy 模型的负对数似然，而且逆 logistic 呈现出较小的 $\\sigma$ 值。如果我们将这两条增长曲线与原始数据进行对比，就可以更清楚地看到它们之间的差异[@fig-5-4]。此外，对各自的残差进行检验也会发现曲线之间的差异，预测的 von Bertalanffy 曲线的残差呈圆弧状，这与其预测的初始长度与生长增量之间的线性关系是一致的。在 @fig-5-4 中，线性回归绘制在 von Bertalanffy 曲线的上方，以说明它实际上是重合的。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #growth curves and regression fitted to tagging data Fig 5.4  \nparset(margin=c(0.4,0.4,0.05,0.05))  \nplot(bi$l1,bi$dl,type=\"p\",pch=16,cex=1.0,col=3,ylim=c(-2,31),  \n     ylab=\"Growth Increment mm\",xlab=\"Length mm\",panel.first=grid())  \nabline(h=0,col=1)  \nlines(bi$l1,predvB,pch=16,col=1,lwd=3,lty=1)  # vB  \nlines(bi$l1,predil,pch=16,col=2,lwd=3,lty=2)  # IL  \nabline(linm,lwd=3,col=7,lty=2) # add dashed linear regression  \nlegend(\"topright\",c(\"vB\",\"LinReg\",\"IL\"),lwd=3,bty=\"n\",cex=1.2,  \n                    col=c(1,7,2),lty=c(1,2,2))  \n```\n\n::: {.cell-output-display}\n![黑岛黑唇鲍标记数据的von Betalanffy（黑色）、逆 logistic （红色曲线虚线）和线性回归（黄色虚线）拟合。\n标记与回捕之间的时间间隔为 1.02 年。显然，vB 和线性回归是相同的。](05-staticModel_files/figure-pdf/fig-5-4-1.pdf){#fig-5-4 fig-pos='H'}\n:::\n:::\n\n\n\n两条生长曲线的残差也显示了各自模型拟合的差异。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #residuals for vB and inverse logistic for tagging data Fig 5.5  \nparset(plots=c(1,2),outmargin=c(1,1,0,0),margin=c(.25,.25,.05,.05))  \nplot(bi$l1,(bi$dl - predvB),type=\"p\",pch=16,col=1,ylab=\"\",  \n     xlab=\"\",panel.first=grid(),ylim=c(-8,11))  \nabline(h=0,col=1)  \nmtext(\"vB\",side=1,outer=FALSE,line=-1.1,cex=1.2,font=7)  \nplot(bi$l1,(bi$dl - predil),type=\"p\",pch=16,col=1,ylab=\"\",  \n     xlab=\"\",panel.first=grid(),ylim=c(-8,11))  \nabline(h=0,col=1)  \nmtext(\"IL\",side=3,outer=FALSE,line=-1.2,cex=1.2,font=7)  \nmtext(\"Length mm\",side=1,line=-0.1,cex=1.0,font=7,outer=TRUE)  \nmtext(\"Residual\",side=2,line=-0.1,cex=1.0,font=7,outer=TRUE)  \n```\n\n::: {.cell-output-display}\n![黑岛黑唇鲍标记数据的 von Betalanffy 曲线残差图（左侧）和 逆 Logistic 曲线残差图（右侧）。标记与回捕之间的时间间隔为 1.02 年。](05-staticModel_files/figure-pdf/fig-5-5-1.pdf){#fig-5-5 fig-pos='H'}\n:::\n:::\n\n\n\n### 对 Fabens 方法的深入探讨\n\nvon Bertalanffy 方程的 Fabens 变换所描述的生长曲线使用了相同的参数，但却暗藏了一些不易察觉的差异。您一定还记得我们使用两种不同的残差误差结构拟合 vB 曲线的例子，这使得结果无法比较，或者更严格地说，无法比较。Fabens 变换改变了残差结构以及参数之间的相互作用方式。取而代之的是 $L_{\\infty}$ 变成了绝对最大值，这就是它能预测负增长的原因。严格来说，Fabens 模型的参数与 von Bertalanffy 模型的参数含义不同。\n\n我们对 von Bertalanffy 曲线和逆 logistic 曲线进行了比较，但由于我们使用了鲍鱼种群的数据作为例子，我们对哪条曲线可能更有用的看法有失偏颇。在大多数有鳞鱼类渔业中，人们发现 von Bertalanffy 曲线作为对生长的一般描述是最有用的，尽管它还存在一些问题。但所有生长模型（不只是标记生长模型）的一个普遍问题是我们迄今为止所使用的假设，即围绕预测生长趋势的观测变化将是恒定的。如果我们看一下 @fig-5-3 或 @fig-5-4 ，还记得我们在第 [-@sec-paraestimat] 章“[模型参数估计](04-application.qmd)”中绘制的年龄长度数据，那么在每种情况下，初始长度或年龄的变化趋势都比较明显。与其坚持在残差中使用恒定的方差（如 SSQ 所要求的），不如使用恒定的变异系数（ $\\sigma/\\mu$ ）。如果我们使用最大似然法，就有可能对残差的方差进行单独建模，从而得出一系列不同的结果；Francis（1988 ）正是这样做的。他使用最大似然法对数据进行了标记模型拟合，并假定每种情况下的残差都是正态分布的，但他对残差方差与期望 $\\Delta L$ 之间的关系提出了一些不同的函数形式（与初始长度的函数关系也是可能的）。迄今为止，我们使用的方法假定方差为常数，因此我们估算了一个常数 $\\sigma$ 参数。Francis（1988）则建议，方差可以有一个介于 $\\sigma$ 和 $\\Delta L$ 之间的恒定乘数，标记数据之间可以存在反比关系。这些考虑因素也适用于年龄-长度模型，在这种模型中，常数乘数将使年龄与 $\\sigma$ 之间呈线性关系。\n\n$$\n\\sigma = \\upsilon (\\Delta \\hat{L})\n$$ {#eq-5_5}\n\n其中 $\\upsilon$ 是期望 $\\Delta L$ 的常数乘数，需要分别估算。此时正态似然将变为：\n\n$$\nL\\left( \\Delta L|Data \\right)=\\sum\\limits_{i}{\\frac{1}{\\sqrt{2\\pi }\\upsilon \\Delta \\hat{L}}}\\exp \\left( \\frac{{{\\left( \\Delta L-\\Delta \\hat{L} \\right)}^{2}}}{2{{\\left( \\upsilon \\Delta \\hat{L} \\right)}^{2}}} \\right)  \n$$ {#eq-5_6}\n\n其中用 $2\\left(\\upsilon \\Delta \\hat L \\right)^2$ 替代一般正态似然的 $\\sigma^2$。除这一简单的替代方案外，Francis（1988 ）还建议对标记数据采用指数递减的残差标准差，再加上一个可估算的常数 $\\tau$ ：\n\n$$\n\\sigma = \\tau \\left( 1 - e^{-\\upsilon (\\Delta \\hat{L})}  \\right)  \n$$ {#eq-5_-_7}\n\n最后，Francis（1988）建议采用幂律描述的残差标准差：\n\n$$\n\\sigma = \\upsilon (\\Delta \\hat{L})^\\tau  \n$$ {#eq-5_8}\n\nFrancis（1988）还通过考虑偏差、生长率的季节性变化以及离群污染的影响，将 Fabens 方法扩展到分析标记数据。文献中往往只强调了报告的一个方面，这也是经常查阅原始文献而不是依赖其他论文或书籍（如这本书）中的摘要的一个很好的理由。如果需要对标记数据拟合生长曲线，Francis（1988）是一个很好的起点。\n\n由于方差与预期 $\\Delta L$ 之间关系的表达不同，常数 $\\tau$ 和 $\\upsilon$ 的解释也发生变化。 如前所述，如果假定的误差结构不同，从同一模型中得到的参数估计值也会不同，从而变得不可比较。遗憾的是，如何选择最合适的误差结构并不是一个简单的问题。充其量，无论选择哪种曲线，使用非恒定方差都能提供与之相关的不确定性的另一种视角。\n\n### 非恒定方差的实现\n\n通过包含期望 $\\Delta L$ 和 残差方差之间关系，我们需要改变包装函数，围绕如何使用预测值 $\\Delta \\hat L$ 计算负对数似然。之前，对于常数 $\\sigma$ 我们用 `negNULL()` ，所以我们可从它开始修改。我们所做的只是包括一个额外函数 `funksig()` ，作为 `negnormL()` 的参数（参见其帮助和代码），从而包括 sigma 值的计算。通过这种方法，我们可以在 `funksig()` 中保留常数 $\\sigma$ 的长版本。但这也表明函数的行为符合预期。然后，我们可以加入一个替代的 `funksig()`，实现上述三个选项之一（或我们自己设计的选项）。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   # fit the Fabens tag growth curve with and without the option to   \n # modify variation with predicted length. See the MQMF function  \n # negnormL. So first no variation and then linear variation.   \nsigfunk <- function(pars,predobs) return(tail(pars,1)) #no effect  \ndata(blackisland)  \nbi <- blackisland # just to keep things brief  \nparam <- c(170.0,0.3,4.0); label=c(\"Linf\",\"K\",\"sigma\")  \nmodelvb <- nlm(f=negnormL,p=param,funk=fabens,funksig=sigfunk,  \n               indat=bi,initL=\"l1\",delT=\"dt\")  \noutfit(modelvb,backtran = FALSE,title=\"vB constant sigma\",  \n       parnames = label)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnlm solution:  vB constant sigma \nminimum     :  291.1691 \niterations  :  24 \ncode        :  1 gradient close to 0, probably solution \n              par     gradient\nLinf  173.9677972 9.563666e-07\nK       0.2653003 2.656839e-04\nsigma   3.5861240 1.391768e-05\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsigfunk2 <- function(pars,predo) { # linear with predicted length  \n  sig <- tail(pars,1) * predo      # sigma x predDL, see negnormL  \n  pick <- which(sig <= 0)          # ensure no negative sigmas from   \n  sig[pick] <- 0.01           # possible negative predicted lengths  \n  return(sig)  \n} # end of sigfunk2  \nparam <- c(170.0,0.3,1.0); label=c(\"Linf\",\"K\",\"sigma\")  \nmodelvb2 <- nlm(f=negnormL,p=param,funk=fabens,funksig=sigfunk2,  \n                indat=bi,initL=\"l1\",delT=\"dt\",    \n                typsize=magnitude(param),iterlim=200)  \noutfit(modelvb2,backtran = FALSE,parnames = label,  \n       title=\"vB inverse DeltaL, sigma < 1\")  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnlm solution:  vB inverse DeltaL, sigma < 1 \nminimum     :  288.1933 \niterations  :  64 \ncode        :  2 >1 iterates in tolerance, probably solution \n              par    gradient\nLinf  171.0000001 45579.23697\nK       0.2724177    77.18211\nsigma   0.4139252    19.64508\n```\n\n\n:::\n:::\n\n\n\n请记住，通过改变残差结构，似然值变得不相称，因此我们无法确定哪种拟合效果更好。恒定方差使得 von Bertalanffy 曲线在长度大于 148 左右时有效地保持在数据之上，而变化方差生长曲线大部分时间仍在数据之上，但由于方差随预测长度的减少而向后推近数据。我们可以通过重写 `negnormL()` 来进行实验，使用初始长度而不是预测长度。如前所述，将平均预测长度与相关方差分离可以获得极大的灵活性。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #plot to two Faben's lines with constant and varying sigma Fig 5.6  \npredvB <- fabens(modelvb$estimate,bi)  \npredvB2 <- fabens(modelvb2$estimate,bi)  \nparset(margin=c(0.4,0.4,0.05,0.05))  \nplot(bi$l1,bi$dl,type=\"p\",pch=1,cex=1.0,col=1,ylim=c(-2,31),  \n     ylab=\"Growth Increment mm\",xlab=\"Length mm\",panel.first=grid())  \nabline(h=0,col=1)  \nlines(bi$l1,predvB,col=1,lwd=2)         # vB  \nlines(bi$l1,predvB2,col=2,lwd=2,lty=2)  # IL  \nlegend(\"topright\",c(\"Constant sigma\",\"Changing sigma\"),lwd=3,  \n       col=c(1,2),bty=\"n\",cex=1.1,lty=c(1,2))  \n```\n\n::: {.cell-output-display}\n![与黑岛黑唇鲍标记数据拟合的具有恒定 sigma von Bertalanffy（皇家蓝）和\n具有与不断变化的 DeltaL 相关的 sgima 的 von Bertalanffy（红色虚线）。\n标记与再捕之间的平均时间间隔为 1.02 年。](05-staticModel_files/figure-pdf/fig-5-6-1.pdf){#fig-5-6 fig-pos='H'}\n:::\n:::\n\n\n\n我们的眼睛习惯于欣赏对称性，因此 @fig-5-6 中不断变化的变化线看起来拟合得相对较差。但是，假设误差只存在于 y 轴上（y-on-x 问题），并且残差的方差也在不断变化，作为拟合模型的反映，下部的红色虚线使数据的值内有一条内在的曲线。使用更复杂的残差结构使模型拟合对初始条件更敏感。您会注意到，在输出结果中，假设残差方差恒定只需要 20-30 次迭代，而使用方差函数关系则需要两倍的迭代次数（这是在使用 Typsize 可选参数来增强稳定性的情况下，而在更简单的模型中没有使用）。如果修改这些起始值，很容易得到难以置信的答案。\n\n尽管在使用年龄长度数据时，特别是在非常小的年龄段，变化的差异往往很明显，但在建模中引入这种复杂性还是需要有充分的理由。\n\n## 目标模型选择 {#sec-label}\n\n在第 [-@sec-paraestimat] 章“[模型参数估计](04-application.qmd)（*Model Parameter Estimation*） ”中，我们看到了一个类似的章节，其中介绍了基于平方和的 Akaike 信息准则（AIC；Akaike，1974）的信息理论近似值（Burnham 和 Anderson，2002）。现在我们使用最大似然法，我们将介绍 AIC 的原始版本，并讨论似然比。\n\n### Akaike 信息准则\n\n在试图描述数据集中的模式时，选择使用哪种模型时，使用的参数数量与模型拟合数据集的质量之间的权衡始终是一个问题。经典的方法是选择最简单的模型，该模型能很好地描述该模式（奥卡姆剃刀只是一个关于简约性的劝告，因此如果两个模型产生的结果相同，就选择最简单的一个）。但是，“等效结果 ”到底有多接近，“最简单 ”又是什么意思。Akaike 的解决方案（1974）是将似然比和 “模型内独立调整参数的数量 ”结合起来使用。AIC 是一种基于似然值的惩罚性模型选择标准，最小的 AIC 表示最佳模型（在似然值与参数数量之间取得平衡）。\n\n$$\nAIC = -2 \\log(L) + \\alpha p\n$$ {#eq-5_9}\n\n其中， $\\log(L)$ 是总对数似然值， $p$ 是拟合模型时显式调整的参数数量，而 $\\alpha$ 是一个乘数（惩罚项，在惩罚似然中），其值由 Akaike（1974）设定为 2.0，这是基于信息论的一个论点。强调“独立调整的参数”是“显式调整的”是为了避免混淆那些保持不变或从其他参数和模型变量推导出来的模型参数（我们在过剩产量模型中的捕获率参数中会看到一个例子）。例如，在渔业模型中一个常见的假设是自然死亡率，通常表示为 $M$，是一个常数。因此，在 AIC 的 $p$ 值中不会将其计算在内。将 $\\alpha$ 作为惩罚项的显式标识，而不是直接使用常数值 2.0，是为了强调关于应使用的确切值存在争议（Bhansali 和 Downham, 1977；Schwartz, 1978；Akaike, 1979；Atkinson, 1980），以确保模型复杂度（参数数量）与拟合质量（最大似然或最小平方和）之间的平衡能够反映模拟中的实际情况。 尽管统计论据相对较为密集，最终归结为 $\\alpha$ 的值 $p$ 应该多大？这一结果被称为施瓦茨的贝叶斯信息准则，简称 BIC。\n\n$$\nBIC = -2 \\log(L) + \\log(n) p\n$$ {#eq-5_10}\n\n其中 $n$ 是样本大小或模型拟合的数据点数， $p$ 是参数数量。只要数据点数大于或等于 8（ $\\log(8)=2.079$），BIC 将比 AIC 更严厉地惩罚复杂模型。另一方面，从直观上讲，考虑样本大小是有道理的。如果我们使用 MQMF 函数 `aicbic()` 对 von Bertalanffy 模型和逆逻辑斯蒂模型的拟合结果进行比较，其中使用了常数 $\\sigma$ 估计 [@fig-5-4]，逆逻辑斯蒂模型的 AIC 和 BIC 均较小，因此在这种情况下，逆逻辑斯蒂模型将是更优的选择。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #compare the relative model fits of Vb and IL  \ncat(\"von Bertalanffy \\n\")  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvon Bertalanffy \n```\n\n\n:::\n\n```{.r .cell-code}\naicbic(modelvb,bi)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     aic      bic    negLL        p \n588.3382 596.3846 291.1691   3.0000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"inverse-logistic \\n\")  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ninverse-logistic \n```\n\n\n:::\n\n```{.r .cell-code}\naicbic(modelil,bi)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     aic      bic    negLL        p \n562.0244 572.7529 277.0122   4.0000 \n```\n\n\n:::\n:::\n\n\n\n### 似然比检验\n\n可以使用广义似然比检验（Neter et al, 1996）来比较不同模型拟合效果与复杂度之间的差异。该方法依赖于似然比检验在样本量增大时渐近趋近于 $\\chi^2$ 分布的事实。这意味着在通常的渔业数据量下，这种方法只是近似的方法。似然比检验正如其名所示，是两个似然性的比值的对数，或者直接处理对数似然性时，是两个对数似然性的相减，两者是等价的（当然，这两个似然性必须来自同一个概率密度函数）。我们希望确定两个使用相同数据和残差结构但模型结构不同的模型（即不同的参数），哪一个能显著更好地拟合可用数据。由于似然比可以由 $\\chi^2$ 分布描述，因此可以正式回答这个问题。 因此，对于两个模型的似然性，如果它们要么具有相同数量的参数，要么仅相差一个参数，在考虑显著性差异时，它们的比值需要大于所需的自由度（不同参数的数量）对应的 $\\chi^2$ 分布。\n\n$$\n\\begin{split}\n-2 \\times \\log\\left[\\dfrac{L(\\theta)_{\\alpha}}{L(\\theta)_b} \\right] &\\le \\chi_{1,1 -\\alpha}^2 \\\\\n-2 \\times [LL(\\theta)_a -LL(\\theta)_b & \\le \\chi_{1,1-\\alpha}^2\n\\end{split}\n$$ {#eq-5_11}\n\n其中 $L(\\theta)_x$ 是模型 $x$ 的 $\\theta$ 参数的似然， $LL(\\theta)_x$ 是等效的对数似然。 $\\chi_{1, 1-\\alpha}^2$ 是 $\\chi^2$ 分布的 $1-\\alpha$ 百分位数（例如，对于 95% 的置信区间， $\\alpha = 0.95$ 和 $1-\\alpha = 0.05$ ，即 $\\chi_{1,1-\\alpha}^2= 3.84$。\n\n简而言之，如果我们要比较两个仅相差一个或没有参数的模型，那么如果它们的负对数似然值相差超过 1.92（3.84/2），则可以认为这两个模型在统计上显著不同，其中一个模型将比另一个模型提供显著更好的拟合。如果两个模型之间相差两个参数，那么这两个模型在统计上显著不同的负对数似然值的最小差异需要达到 $2.995(5.99/2)=\\chi_{2, 0.95}^2/2$ 自由度为 2），依此类推，对于参数差异更多的情况（Venzon 和 Moolgavkar, 1988）。\n\n关于 von Bertalanffy 曲线和逆逻辑斯蒂曲线的比较，逆逻辑斯蒂负对数似然值为 $-2.0 \\times(277.0122-291.1691) = 28.3138$ ，明显小于 von Bertalanffy 曲线的负对数似然值。我们可以使用 MQMF 函数 `likeratio()`来说明这两种曲线在拟合数据方面的差异具有高度显著性。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # Likelihood ratio comparison of two growth models see Fig 5.4  \nvb <- modelvb$minimum # their respective -ve log-likelihoods  \nil <- modelil$minimum  \ndof <- 1  \nround(likeratio(vb,il,dof),8)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         LR           P      mindif          df \n28.31380340  0.00000005  3.84145882  1.00000000 \n```\n\n\n:::\n:::\n\n\n\n### 似然比检验的注意事项\n\n由于在渔业模型中广泛使用加权对数似然，当使用似然比检验来比较替代模型时，需要小心确保这些模型实际上是可比的。当我们使用相同的数据和相同的概率密度函数来描述残差分布时，可以使用似然比检验。但请记住，当我们仅对相同的生长模型应用不同的残差误差结构假设（对数正态而非正态）时，这些曲线是完全不可比的（不具可比性）。同样，在使用惩罚似然时，不同版本的模型可能会对不同的数据流给予不同的权重，这种变化使得模型不可比。很明显，应该只比较可比的模型，但在一些更复杂的模型中，确定什么是公平比较有时并不总是简单的。\n\n## 关于生长的说明\n\n对个体生长过程的描述对渔业模型很重要，因为个体的大小和重量的生长是特定种群生产力的重要组成部分。这种生长显然是增加种群生物量过程与减少种群生物量过程之间平衡的一个积极因素。但重要的是要理解，生长的描述总是描述性的，并且主要适用于我们有数据的大小范围。有许多实例表明，von Bertalanffy 曲线外推的弱点会导致生物学上荒谬的预测（Knight，1968）。但这类实例是将模型参数的特定解释误认为现实，而曲线仅仅是生长数据的描述，严格来说只在有数据的地方有效。这就是为什么已经产生了生长模型转换，这些转换估计的参数可以位于可用数据的范围内（Schnute，1981；Francis，1988，1995）。\n\n## 成熟\n\n### 引言\n\n目前，渔业管理倾向于使用所谓的生物参考点来构建其希望构成合理且可辩护的管理决策的基础，这些决策针对的是可再生的自然资源（FAO，1995，1996，1997；Restrepo 和 POwers，1999；Haddon，2007）。简单来说，这个想法是设定一个目标参考点，通常定义为成熟生物量水平或其某种替代指标，该指标被认为是种群的一种理想状态。它是理想状态，因为通常它应该能够为后续的补充提供良好的水平，并为种群提供足够的恢复力以抵御偶尔的环境冲击。常见的默认值可以是 $B_{40}$，即 $40\\% B_0$，或 40% 的消耗水平，这被用作 $B_{MSY}$ 的替代指标，或者是能够可持续产生最大可持续产量的产卵生物量。在澳大利亚，联邦收获策略政策将目标定义为 $B_{48}$，这被用作 $B_{MEY}$ 的替代指标，即应该能够产生最大经济效益的产卵生物量（注意，目标是生物量水平 $B_{MSY}$，而不是 $MEY$；DAFF，2007；Rayns，2007）。 此外，还需定义一个极限参考点，同样以成熟生物量（或替代指标）的水平来表示，低于该水平时，所关注的种群将被认为其补充量存在受损害的风险。生物参考点通常以未受干扰的产卵生物量的估计值（ $B_0$ ）为基准来表述。 $B_0$ 的概念可以是均衡概念，也可以是更动态的版本，试图解释补充量的变化。无论哪种情况，这个数值在评估中往往具有不确定性，并且在不同评估中经常发生变化（Punt 等，2018 ）。为了提供管理建议，需要三个要素：\n\n-   对当前种群状态进行评估，包括繁殖生物量的消耗情况，从而\n\n-   当前未捕捞的产卵生物量估计值，最后\n\n-   一个决定下一个季节（些）允许的捕捞死亡率、努力量或渔获量的捕捞控制规则。\n\n也许你注意到了，我在成熟和产卵生物量这两个术语之间互换使用。这样做并不是想让你感到困惑，而是想让你习惯于文献中会遇到的术语变化。\n\n强调成熟生物量或产卵生物量的重要性，是获得合理成熟大小或年龄估计的原因。这是为了确保对成熟生物量有多少的估计能够反映鱼种的生物学特性以及当前渔业状态。在本书中，我们试图专注于建模，但始终试图模拟潜在的生物学现实。事实上，生物学现实，就像生长的细节一样，往往相当复杂。在渔业理论中，许多基础来自北半球，特别是对北海和大西洋的高生产力鱼种进行研究（Smith，1994）。那里的许多商业物种具有相对简单的繁殖历史。有雄性和雌性，作为一个种群，它们按一般节律成熟，它们在死亡之前要么产卵一次，要么每年产卵。当然，这是一种过度简化，生物学世界比这要多样化得多，即使在北半球也是如此。 有些物种从一开始就是雌性，其中一些较大的雌性会转变为雄性（原雌雄同体），反之亦然（原雄雌同体）。存在许多不同的繁殖策略，其中许多策略会影响诸如成熟大小和/或年龄等因素。然而，在这里我们将只关注经典方法。尽管如此，使用你自己的例子时，不要对生物学做出假设，始终情况下，来自种群的代表性证据比假设更好。\n\n成熟时的个体大小或年龄是一个种群特性。个体可能经历成熟过程，并需要时间才能具备繁殖能力，但我们描述的过程是针对整个种群的平均值。给定一个样本，希望是一个足够大的样本，能够覆盖成熟时个体大小或年龄的范围，我们的目标是描述每个个体大小或年龄的鱼类中成熟的比例。成熟时个体大小（size-at-maturity ）的概念通常被总结为 种群中50% 个体性成熟（具备繁殖能力）时的个体大小。实际上， $Lm_{50}$ ，即 50% 成熟的个体长度，只是重要因素的一部分，此外，正如我们将看到的，关于物种随长度或年龄成熟的速度的某种度量也同样重要。一些更简单的渔业模型仍然使用一种被称为“刀刃式成熟”（knife-edge matruity）的假设，这意味着一个强烈的假设，即 100% 的动物在某个特定年龄成熟。我们将在后面讨论种群成熟所需的时间如何影响种群动态。 如何确定成熟度在此不予考虑，尽管理想情况下应使用组织学来确认成熟的配子，而不是仅仅通过观察鱼类的性腺。再次强调，有大量文献致力于详细说明确定各种物种成熟阶段的细节，但我们不会尝试去探讨这些内容。我们所要完成的任务是找到预期种群成熟曲线的数学描述。预期的是，被认为成熟的动物比例会随着体型和年龄的增长而增加，直到 100%成熟（尽管即使对此也有例外，某些物种的雌性会花几年时间从产生卵子所需的大量能量投资中恢复，从而暂时停止繁殖）。生命史特征体现在物种是适应一次性繁殖（半繁殖性）还是多次繁殖（多次繁殖性），或者它产生的是大量小卵还是远少得多的大卵，甚至生产少量活体幼崽。始终要记住，生物学可以非常复杂，而生物学的数学描述是相对简单的抽象。\n\n### 替代的成熟度曲线\n\n一个种群内成熟的一般模式是，成熟度会分布在一系列长度和年龄中，其中一部分早熟，一部分晚熟，大多数则在某个平均时间成熟。如果我们想象一个随时间变化的成熟比例的抛物线曲线，可能接近正态分布但尾部更短，那么我们想要的是该分布的累积密度函数，在某个长度或年龄范围内从 0% 到 100% 运行。结果是常见的 S 形曲线，通常称为逻辑斯蒂曲线，在文献中，有大量不同的数学表达式来描述这类曲线。我们关注的统计量是 $Lm_{50}$ （50%成熟的大小/年龄），以及 $IQ$ ，即四分位距，它衡量成熟度曲线（在 25%和 75%成熟时的年龄）之间的大小/年龄范围。使用四分位距是一个任意选择，但反映了常见做法（如箱线图所示），但并不排除使用更宽或更窄的范围，如果这些范围更方便的话。\n\n在众多不同版本中，有一个经典的逻辑斯蒂曲线 [@eq-5_12]，常用于描述许多种群的成熟过程（参见 **MQMF** 函数）。这种形式非常适合使用具有二项式误差的广义线性模型进行拟合。我们一直使用 R 作为编程环境，但这里是一个提醒我们，它的最初目的是作为统计分析工具的机会。\n\n$$\np_L = \\dfrac{\\exp(a +bL)}{1+ \\exp(a +bL)} = \\dfrac{1}{1+\\exp(a +bL)^{-1}}\n$$ {#eq-5_12}\n\n$p_L$ 是长度 $L$ 的成熟比例，而 $a$ 和 $b$ 是指数参数。请注意，我在方程中未包含误差项。这里我们试图对不同个体大小（为简洁起见，我将停止每次写“尺寸或年龄”）的成熟或不成熟观测进行预测。这正是建议我们应使用二元误差的原因，如模型参数估计章节所述。这种公式的另一个优点是 $Lm_{50} = -a/b$ ，即 50% 成熟时的个体大小，可以直接从参数中推导出来。类似地，四分位距也可以从参数中推导出来，表示为 $IQ = 2\\times \\log(3)/b = 2.197225 \\times b$。\n\n成熟数据具有二元特性，在特定采样时间对种群进行采样时，观测值是每个大小为 $L$ 的采样鱼是否成熟。本书的 R 包 **MQMF** 包含一个示例数据集 tasab，其中包含来自塔斯马尼亚海岸线 16 公里段上两个地点的黑唇鲍鱼（*Haliotis rubra*）数据。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   # The Maturity data from tasab data-set  \ndata(tasab)       # see ?tasab for a list of the codes used  \nproperties(tasab) # summarize properties of columns in tasab  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Index isNA Unique     Class Min Max Example\nsite       1    0      2   integer   1   2       1\nsex        2    0      3 character   0   0       I\nlength     3    0     85   integer  62 160     102\nmature     4    0      2   integer   0   1       0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(tasab$site,tasab$sex) # sites 1 & 2 vs F, I, and M  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   \n      F   I   M\n  1 116  11 123\n  2 207  85 173\n```\n\n\n:::\n:::\n\n\n\n鲍鱼因其生物学特征在相对较小的空间尺度上具有高度变异性而臭名昭著，因此采样地点的细节非常重要（Haddon 和 Helidoniotis，2013）。这些数据都是由同一群人在同一个月同年收集的，因此除了壳长之外，我们唯一可能认为会影响成熟度的因素就是具体地点（性别似乎在同一时间、同一个体大小成熟； @fig-5-7 ）。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   #plot the proportion mature vs shell length  Fig 5.7  \npropm <- tapply(tasab$mature,tasab$length,mean) #mean maturity at L  \nlens <- as.numeric(names(propm))            # lengths in the data  \nplot1(lens,propm,type=\"p\",cex=0.9,xlab=\"Length mm\",  \n      ylab=\"Proportion Mature\")  \n```\n\n::: {.cell-output-display}\n![tasab 数据集中黑唇鲍鱼成熟数据的长度成熟比例。](05-staticModel_files/figure-pdf/fig-5-7-1.pdf){#fig-5-7 fig-pos='H'}\n:::\n:::\n\n\n\n数据看起来相对嘈杂，虽然这很难判断，因为一些观察到的长度，其成熟比例不是 0 也不是 1，可能只有少数几次观测。例如，在长度为 100mm 处有一个成熟比例为 0.5 的点，如果你深入数据会发现该点仅由两个观测组成，一个成熟另一个不成熟。可以通过 `pick <- which(tasab$length == 100)` 查找这些长度，或者通过 `which(propm == 0.5)` 查看数据，再使用 `tasab[pick,]`进一步分析。\n\n使用 `properties(tasab)` 或 `head(tasab,10)` 查看数据集，可以告诉我们有哪些变量。虽然我们显然希望检查成熟和长度之间的关系，但请记住，最初我们还想检查站点对成熟的影响。重要的是，我们需要将站点变量转换为分类因子，否则它将被视为包含 1 和 2 的整数向量，而不是潜在的不同处理。我们不能将性别作为因子包括进来，因为所有动物最初都是未成熟状态，尽管可以始终分别分析雄性和雌性数据。然而，在更多的站点上，到目前为止，在黑唇牡蛎中，尚未发现性别在成熟速率或平均大小上的可重复差异。一旦拟合，我们会发现站点对分析无信息性（它不显著），因此我们重新进行不包括站点的分析。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #Use glm to estimate mature logistic  \nbinglm <- function(x,digits=6) { #function to simplify printing  \n  out <- summary(x)  \n  print(out$call)  \n  print(round(out$coefficients,digits))  \n  cat(\"\\nNull Deviance  \",out$null.deviance,\"df\",out$df.null,\"\\n\")  \n  cat(\"Resid.Deviance \",out$deviance,\"df\",out$df.residual,\"\\n\")  \n  cat(\"AIC  = \",out$aic,\"\\n\\n\")  \n  return(invisible(out)) # retain the full summary  \n} #end of binglm  \ntasab$site <- as.factor(tasab$site) # site as a factor  \nsmodel <- glm(mature ~ site + length,family=binomial,data=tasab) \nouts <- binglm(smodel)  #outs contains the whole summary object  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglm(formula = mature ~ site + length, family = binomial, data = tasab)\n              Estimate Std. Error   z value Pr(>|z|)\n(Intercept) -19.797096   2.361561 -8.383056 0.000000\nsite2        -0.369502   0.449678 -0.821703 0.411246\nlength        0.182551   0.019872  9.186463 0.000000\n\nNull Deviance   564.0149 df 714 \nResid.Deviance  170.7051 df 712 \nAIC  =  176.7051 \n```\n\n\n:::\n\n```{.r .cell-code}\nmodel <- glm(mature ~ length, family=binomial, data=tasab)  \noutm <- binglm(model)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nglm(formula = mature ~ length, family = binomial, data = tasab)\n              Estimate Std. Error   z value Pr(>|z|)\n(Intercept) -20.464131   2.265539 -9.032787        0\nlength        0.186137   0.019736  9.431291        0\n\nNull Deviance   564.0149 df 714 \nResid.Deviance  171.3903 df 713 \nAIC  =  175.3903 \n```\n\n\n:::\n\n```{.r .cell-code}\ncof <- outm$coefficients  \ncat(\"Lm50 = \",-cof[1,1]/cof[2,1],\"\\n\")  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLm50 =  109.9414 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"IQ   = \",2*log(3)/cof[2,1],\"\\n\")  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIQ   =  11.80436 \n```\n\n\n:::\n:::\n\n\n\n在第一次分析中，包括了站点因素，因为我在汇总数据时确保所包含的站点相似，因此站点 2（P=0.411）与站点 1 没有显著差异，这意味着在这种情况下，站点因素对分析来说并不具有信息性。因此，我们再次进行了分析，将站点从方程中剔除。如果站点之间表现出显著差异，那么我们需要使用多个曲线来描述模型结果。无论怎样，我们还是会将它们画成不同的曲线来说明过程。额外的站点参数是对初始指数截距值的修饰。因此，ab\\$length 参数在两种情况下都是 $b$ 参数，但站点 1 的曲线可以通过将截距视为 $a$ 参数来获得，而站点 2 的曲线则需要将截距和 ab\\$site2 的参数值相加，作为 $a$ 参数。因此，站点 1 模型为 $a = -19.797$ 和 $b = 0.18255$ ，而站点 2 模型为 $a = -19.797 -0.3695$ 和 $b = 0.18255$ 。将最终无站点模型添加到图中表明，综合模型更接近站点 2，这反映了站点 2 的观测次数为 465 次，而站点 1 仅为 250 次。 注意，参数少一个后，残差偏差略有增加，但尽管如此，包含站点因子的模型的 AIC 值仍然大于简化模型的 AIC 值，这再次表明简化模型在复杂性和模型拟合度之间提供了更好的平衡。这与广义线性模型及其比较和操作有明显的类比。如果确实发现截距之间存在显著差异，那么测试差异是否也扩展到 $b$ 参数，以确定是否需要完全分开处理这些曲线是有意义的。共享公共参数通常是有帮助的，因为它可以增加样本量。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #Add maturity logistics to the maturity data plot Fig 5.8  \npropm <- tapply(tasab$mature,tasab$length,mean) #prop mature  \nlens <- as.numeric(names(propm))       # lengths in the data  \npick <- which((lens > 79) & (lens < 146))  \nparset()\nplot(lens[pick],propm[pick],type=\"p\",cex=0.9, #the data points  \n      xlab=\"Length mm\",ylab=\"Proportion Mature\",pch=1)   \nL <- seq(80,145,1) # for increased curve separation  \npars <- coef(smodel)  \nlines(L,mature(pars[1],pars[3],L),lwd=3,col=3,lty=2)    \nlines(L,mature(pars[1]+pars[2],pars[3],L),lwd=3,col=2,lty=4)    \nlines(L,mature(coef(model)[1],coef(model)[2],L),lwd=2,col=1,lty=1)    \nabline(h=c(0.25,0.5,0.75),lty=3,col=\"grey\")\nlegend(\"topleft\",c(\"site1\",\"both\",\"site2\"),col=c(3,1,2),lty=c(2,1,4),  \n       lwd=3,bty=\"n\")  \n```\n\n::: {.cell-output-display}\n![黑唇牡蛎成熟度数据（tasab 数据集）的长度成熟比例。不考虑站点的综合分析（两者）更接近站点 2（点划线）而非站点 1（划线），这反映了站点 2 样本量更大。](05-staticModel_files/figure-pdf/fig-5-8-1.pdf){#fig-5-8 fig-pos='H'}\n:::\n:::\n\n\n\n大样本量通常能提高模型拟合的质量。如果有足够的数据，当前数据所表现出的变异性可能会被充分降低，从而可以在这些站点之间找到统计学上的显著差异。然而，如果我们考虑站点 1 和站点 2 的 $Lm_{50}$ 差异约为 2 毫米（总共 110 毫米），从生物学角度来看，这种差异可能并不重要，因为两个站点之间的生长速率也可能不同。正如任何模型或统计分析一样，在关注统计显著性的同时，还应考虑生物学意义。\n\n### 对称性假设\n\n在很多情况下，标准逻辑曲线很好地描述了从未成熟到成熟（或者可能是其他生物过渡，如隐性到显性、 molt 阶段 A 到阶段 B 等）的过程。然而，经典逻辑曲线的主要限制是它在 $L_{50}$ 点对称，这可能不是对现实世界事件的最佳描述。\n\n已经提出了多种替代的非对称曲线，但幸运的是，Schnute 和 Richards（1990）提出了一种通用或统一模型，用于描述“鱼类生长、成熟和存活数据”，这种模型不仅推广了用于描述成熟度的经典逻辑斯谛模型，还推广了 Gompertz（1825）、von Bertalanffy（1938）、Richards（1959）、Chapman（1961）和 Schnute（1981）提出的生长模型，其中一些模型也可以用于描述成熟过程。\n\nSchnute 和 Richards (1990) 模型有四个参数：\n\n$$\ny^{b} = 1+ \\alpha \\exp(-a x^c)\n$$ {#eq-5_13}\n\n可以重新排列， @eq-5_14 ，以更好地展示其与经典的逻辑斯蒂曲线 [@eq-5_12] 的关系，如果我们将两者设置为 $b = c = 1.0$ ，则相当于经典的逻辑斯蒂曲线（例如，设置 $\\alpha = 300$ 和 $a = 0.12$ ）。\n\n$$\ny = \\dfrac{1}{1+ \\alpha \\exp(-a x^c)^{1/b}}\n$$ {#eq-5_14}\n\n如果使用其中一种特殊的经典情况，可能会有解析解来确定 $L_{50}$ 和 $IQ$，但通常情况下需要通过数值方法来找到它们（参见 **MQMF** 函数`bracket()`和 `linter()` ）。这条曲线可以用二项式误差来拟合成熟数据，就像之前那样，尽管可以使用 `nlm()` 或其他非线性求解器（Schnute 和 Richards, 1990 年提供了所需的似然函数）。但特殊情况可能为完整的四参数模型提供更稳定的解。从（5.14）式所示的可能曲线的不对称性，可以很容易地使用 **MQMF** `srug()` 函数（Schnute 和 Richards 统一增长模型）来证明。在没有找到 $L_{50}$ 和 $IQ$ 的解析解时，我们可以使用两个函数 `bracket()` 和 `linter()`，它们界定了目标值（在这种情况下为 0.25、0.5 和 0.75），然后线性插值以生成所需的统计量的近似估计值（参见它们的帮助文件和示例）。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #Asymmetrical maturity curve from Schnute and Richard's curve Fig5.9  \nL = seq(50,160,1)  \np=c(a=0.07,b=0.2,c=1.0,alpha=100)  \nasym <- srug(p=p,sizeage=L)  \nL25 <- linter(bracket(0.25,asym,L))   \nL50 <- linter(bracket(0.5,asym,L))   \nL75 <- linter(bracket(0.75,asym,L)) \nparset()\nplot(L,asym,type=\"l\",lwd=2,xlab=\"Length mm\",ylab=\"Proportion Mature\")  \nabline(h=c(0.25,0.5,0.75),lty=3,col=\"grey\")  \nabline(v=c(L25,L50,L75),lwd=c(1,2,1),col=c(1,2,1))  \n```\n\n::: {.cell-output-display}\n![使用 Schnute 和 Richards 统一生长曲线的假设示例中达到成熟长度的比例。通过绿色虚线所示的四分位距左右两侧的差异，展示了该逻辑斯蒂曲线的不对称性。](05-staticModel_files/figure-pdf/fig-5-9-1.pdf){#fig-5-9 fig-pos='H'}\n:::\n:::\n\n\n\n使用 @fig-5-9 中使用的参数作为基准，我们可以单独改变各个参数来确定其对结果曲线的影响。 $a$ 和 $c$ 参数相对影响四分位距，而所有四个参数都影响 $L_{50}$。\n\nSchnute（1981）的模型在文献中似乎比 Schnute 和 Richards（1990）的更通用的模型使用得更多，这在 Schnute 和 Richards 模型旨在展示所有这些不同曲线可以统一，并因此具有一定程度的共性时是自然的。这强调了这些曲线主要提供的是生物学过程的经验描述，而这些过程本身是所研究种群的涌现属性。严格地对这些参数进行生物学解释，并期望自然界总是提供合理的或有意义的参数值，这是过度推断。例如，Knight（1968）描述的情况，他讨论的是生长，但实际上是在讨论是否应该对经验模型参数进行明确解释。他指出：“更为重要的是，将 $L_{\\infty}$ 视为自然事实，而不是数据分析的产物，会引发扭曲的观点。”（Knight, 1968, p 1306）。 描述性而非解释性的模型（关于过程的假设性描述）仍然是经验性描述，当尝试解释其参数时需要格外小心。\n\n## 补充量\n\n### 引言\n\n种群生物量生产的主要贡献者包括新个体对种群的补充和个体的生长（其中，种群的定义意味着我们无需考虑迁入）。再次强调，关于补充过程的文献非常丰富（Cushing，1988；Myers 和 Barrowman，1996；Myers，2001），但在这里我们将主要关注在尝试将其动态纳入模型时如何描述它。与其他生长和成熟静态模型一样，这些模型被认为随时间保持不变，尽管在种群评估模型中存在时间分段选项，可以在特定界定的时间段内使用不同的参数集（Wayte，2013）。本节中我们将重点关注简单的描述。\n\n鱼类种群的补充量自然倾向于高度变异，不同物种的变异程度有所不同。如果你觉得我在一句话中频繁使用\"变异\"及相关术语，或许这会强化补充量确实高度变异的观点。渔业科学家面临的主要问题是补充量是由繁殖群体资源量、环境变异或两者的某种组合决定的。这让人回想起 20 世纪 50 年代种群动态学中的争论，即种群是否受密度依赖或密度独立效应的控制（Andrewartha and Birch, 1954）。这个变异问题导致了一种普遍但错误的信念，即在一个观察到的群体规模范围内，渔业的补充量实际上与成鱼群体规模无关。这可能是一个危险的假设（Gulland, 1983）。补充量与繁殖群体资源量之间没有关系的观点认为，科学家和管理者可以忽视群体补充量关系，除非有明确证据表明补充量与群体资源量无关。 种群补充量无关系的观点源于通常情况下关于这种关系的数据显得非常分散，没有明显的特征。\n\n尽管存在争议，但在渔业模型中，对 补充过程的建模仍然具有重要意义。因为用这些模型提供从当前时间点出发的管理建议时，通常会在评估不同捕捞或努力量水平的影响时，将模型动态向前预测。通过在这些预测中包含不确定性，可以估计不同管理方案未能实现预期管理目标的相对风险（Francis，1992）。但要进行此类预测，需要了解鱼群的生产力。假设已包含了个体生长动态，那么对补充量水平的时间序列估计或某种定义的鱼群补充量关系可以用来为这些预测生成未来补充量水平的估计。\n\n在本章中，我们将仅考虑鱼类种群补充量关系的数学描述，并且大多忽略这些关系背后的生物学因素，尽管总会有例外。我们将回顾两种最常用的鱼类种群补充量数学模型，并讨论它们在复杂程度不同的种群评估模型中的应用。\n\n### “良好”种群补充量关系的性质\n\nCushing（1988）为种群补充关系的生物学过程提供了很好的介绍，他概述了卵和幼鱼死亡的原因，并提供了丰富的实例和该主题的参考文献。与其他讨论的基本生产过程一样，关于种群补充量关系的生物学及其调节因素的文献非常丰富。\n\n已有研究已证实多种生物学和物理因素对补充量结果有影响。我们不会考虑任何真实物种的生物学细节，除非指出种群资源量与补充量之间的关系并非决定性，且可能存在多种反馈形式影响结果。已提出多种描述种群补充量关系的数学模型，但我们仅考虑 Beverton 和 Holt 以及 Ricker 的模型，而 Deriso-Schnute（Deriso, 1980; Schnute, 1985）等模型也同样重要。\n\nRicker (1975) 列出了他认为理想的平均种群补充关系的四个特性：\n\n-   种群补充曲线应通过原点；也就是说，当种群数量为零时，补充量应为零。这假设所考虑的观测值与总种群相关，并且不存在由移民组成的“补充”。\n\n-   补充量不应在高种群密度时降至零。这不是一个必要条件，尽管观察到补充量随种群密度增加而下降，但并未观察到补充量降至零的情况。即使种群在最大生物量时达到平衡，补充量仍应与自然死亡率相匹配。\n\n-   补充量率（单位繁殖群体补充量）应随着亲本群体的增加而持续减少。只有当正密度依赖机制（补偿性机制）在起作用时（例如，群体增加导致幼体死亡率增加），这种情况才是合理的。但如果负密度依赖机制（消耗性机制）在起作用（例如，捕食者饱和和 Allee 效应；Begon and Mortimer, 1986），那么这并不总是成立。\n\n-   补充量必须超过亲代种群在亲代种群可能范围的部分。严格来说，这仅适用于在死亡前只繁殖一次的物种（例如鲑鱼）。对于寿命更长、多次繁殖的物种，应解释为补充量必须足够高，以超过因年度自然死亡率造成的损失。\n\nHilborn 和 Walters（1992）提出了另外两种他们认为与良好种群补充关系相关的普遍特性：\n\n-   平均繁殖群体补充量曲线应该是连续的，在群体规模的小幅变化中不应有剧烈变化。他们指的是连续性，即平均补充量应该随着群体规模平滑变化，与上述条件 3 相关。\n\n-   平均种群补充关系的稳定性是随时间不变的。这就是平稳性，即这种关系不会随时间发生显著变化。这一假设在生态系统发生显著变化（其中被开发种群是其中一部分）的系统中可能不成立。但在模型中，可以通过使用参数时间块来处理这种情况（例如，参见 Wayte，2013 年）。\n\n### 补充型过度捕捞\n\n“过度捕捞（overfishing）”这一术语通常在两种情境下进行讨论，即生长型过度捕捞（growth overfishing）和补充型过度捕捞（recruitment overfishing）。生长型过度捕捞是指捕捞强度过大，导致最终大多数个体在相对较小时就被捕捞。这在“单位补充量渔获量”（YPR）方面是一个问题。YPR 的分析着重于平衡因总死亡率导致的种群损失与因个体生长带来的种群增长，旨在确定开始捕捞该物种的最佳个体大小和年龄（这里的“最佳”可以有多种含义）。生长型过度捕捞是指鱼群在没有时间达到这种最佳个体大小之前就被捕获。\n\n补充型过度捕捞发生时，意味着对鱼群捕捞过度，使得繁殖群体规模降低到其作为一个种群无法产生足够的新补充量来替代那些死亡（无论是自然死亡还是其他原因）的个体水平。显然，这种情况不可能持续太久，不幸的是，过度捕捞通常会导致渔业崩溃。虽然需要记住，渔业崩溃通常意味着渔业不再具有经济可行性，但这并不意味着字面意义上的灭绝。\n\n虽然生长型过度捕捞相对容易检测（如果种群处于 YPR 最佳状态？尽管当然，可能会有复杂情况）。不幸的是，对于补充型过度捕捞的检测来说，情况并非如此，这可能需要确定成熟或产卵种群资源量与补充水平之间的关系。这已被证明是许多渔业面临的艰巨任务。相反，随着正式捕捞策略的出现，人们普遍的做法是确定一个被认为对后续补充构成不可接受风险的繁殖生物量水平。一个非常常见的极限参考点是未受干扰繁殖生物量的 20%（ $0.2B_0$）。关于极限参考点耗竭水平 $20 \\% B_0$ 的最早参考似乎来自 Beddington & Cooke (1983)。他们以如下方式解释了他们对不同种群潜在产量分析所施加的限制：\n\n“…使用预期未开发产卵生物量 20%的逃逸水平。这个数字并非保守估计，但它代表了一个较低的限制，即在此水平下可能观察到补充量的下降。”（Beddington & Cooke, 1983, 第 9-10 页）。\n\n导致产生 $B_{20\\%}$（注意 $0.2B_0$ 的不同表示方式）作为潜在过度捕捞指标的一个合理捕捞强度的观念的最具影响力的文件，是一份为美国国家海洋渔业服务局准备的文件（Restrepo 等，1998）。事实上，他们推荐 $0.5B_{MSY}$，但认为 $B20\\%$ 是该数值的一个可接受的替代值。然而，需要注意的是，这只是一个“经验法则”，没有实证基础将替代值 $B_{LIM} =B_{20\\%}$ 或 $0.5B_{MSY}$ 联系起来。实际上，对于某些物种选择 $0.5B_{MSY}$ 可能导致 $B_{LIM}$ 远低于 $B_{20\\%}$。\n\n### Beverton-Holt 补充量\n\n历史上，Beverton 和 Holt（1957）的种群补充曲线因其简单的解释而有用，也就意味着可以从基本原理推导出这种关系。对他们来说，数学上易于处理也很重要，因为当时只有解析方法可行。事实上，它持续使用似乎很大程度上源于惯性和传统。请注意，如果我们仅仅将 Beverton-Holt 曲线视为一种数学描述，那么实际上任何具有前面列出的良好性质的曲线都可以使用。然而，人们谈论“Beverton-Holt 种群补充模型”，但它有多种形式。有两种常见的使用形式：\n\n$$\nR_y = \\dfrac{B_{y-1}}{\\alpha + \\beta B_{y-1}} \\exp \\left(N(0, \\sigma_R^2) \\right)\n$$ {#eq-5_15}\n\n其中 $R_y$ 代表第 $y$ 年的补充量， $B_y$ 代表第 $y$ 年的繁殖生物量， $\\alpha$ 和 $\\beta$ 是两个 Beverton-Holt 参数， $\\exp(N(0, \\sigma^2_R))$ 表示预测模型值与自然观测值之间的关系呈对数正态分布（常表示为 $e^{\\varepsilon}$）。 $\\beta$ 值决定渐近极限（ $=1/\\beta$ ），而 $\\alpha$ 的不同值与每条曲线达到渐近线的速度成反比，从而决定原点附近的相对陡峭程度（一个关键词，我们将会更多地讨论它）（ $\\alpha$ 的值越小， 补充量达到最大值的速度越快）。当然，这是一种平均关系，曲线周围的散布与曲线本身同样重要。一个常见的替代重新参数化公式是：\n\n$$\nR_y = \\dfrac{a B_{y-1}}{b +B_{y-1}} e^{\\varepsilon}\n$$ {#eq-5_16}\n\n其中 $a$ 代表最大最大补充 量（即 $a = 1/\\beta$），而 $b$ 代表为产生平均最大补充量一半（即 $a/2$ ）所需的产卵群体（即 $b = \\alpha/\\beta$ ）。使用 $y-1$ 年的生物量代表产生第 $y$ 年补充量，这会影响产卵时间。如果产卵发生在十二月，而仔稚鱼沉底发生在次年，那么这样是正确的；如果两者发生在同一年，那么显然需要更改下标。需要注意的是，生物学现实，在这种情况下与时间相关，甚至可能渗入非常简单的模型中。数学模型可以提供对自然的绝佳表征，但需要了解所建模动物的生物学特性，以避免简单的错误！\n\n从 @fig-5-11 中可以看出，Beverton–Holt 曲线的初始陡峭程度以及渐近值捕捉了该方程行为的重要方面。渐近线由参数 $a$ 的值给出，而初始陡峭程度则由( $a/b = 1/\\alpha$ )的值近似表示，这发生在 $B_y$ 相对较小时。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #plot the MQMF bh function for Beverton-Holt recruitment  Fig 5.11  \nB <- 1:3000  \nbhb <- c(1000,500,250,150,50)  \nparset()\nplot(B,bh(c(1000,bhb[1]),B),type=\"l\",ylim=c(0,1050),\n      xlab=\"Spawning Biomass\",ylab=\"Recruitment\")  \nfor (i in 2:5) lines(B,bh(c(1000,bhb[i]),B),lwd=2,col=i,lty=i)  \nlegend(\"bottomright\",legend=bhb,col=c(1:5),lwd=3,bty=\"n\",lty=c(1:5))  \nabline(h=c(500,1000),col=1,lty=2)  \n```\n\n::: {.cell-output-display}\n![有恒定 a = 1000 和五个递减的 b 值的Beverton-Holt 种群补充曲线，导致越来越高效的曲线。](05-staticModel_files/figure-pdf/fig-5-11-1.pdf){#fig-5-11 fig-pos='H'}\n:::\n:::\n\n\n\n### Ricker 补充量\n\n由 Ricker（1954，1958）提出了 Beverton-Holt 曲线的替代方案，但这同样有多种参数化方式：\n\n$$\nR_y = a S_ye^{-bS_y}e^{\\varepsilon}\n$$ {#eq-5_17}\n\n其中 $R_y$ 代表 $y$ 年产卵群体 $S_y$ 产生的补充量， $a$ 代表低种群水平时的单位繁殖资源量-补充量， $b$ 与单位繁殖补充量随 $S$ 增加而减少的速率相关。 $e^{\\varepsilon}$ 表示关系与观测数据之间的对数正态残差误差。请注意，参数 $a$ 和 $b$ 与 Beverton–Holt 方程中的参数非常不同。该种群-补充量曲线不会达到渐近线，而是在高种群水平时表现出补充量水平的下降 [@fig-5-12] 。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #plot the MQMF ricker function for Ricker recruitment  Fig 5.12  \nB <- 1:20000  \nrickb <- c(0.0002,0.0003,0.0004) \nparset()\nplot(B,ricker(c(10,rickb[1]),B),type=\"l\",xlab=\"Spawning Biomass\",  \n               ylab=\"Recruitment\")  \nfor (i in 2:3)   \n   lines(B,ricker(c(10,rickb[i]),B),lwd=2,col=i,lty=i)  \nlegend(\"topright\",legend=rickb,col=1:3,lty=1:3,bty=\"n\",lwd=2)  \n```\n\n::: {.cell-output-display}\n![两条具有相同常数 $a=10$ 但具有不同 $b$ 值的 Ricker 种群补充量曲线。请注意， $b$ 值主要影响补充量随生物量增加而下降的水平，对初始陡峭程度影响较小。](05-staticModel_files/figure-pdf/fig-5-12-1.pdf){#fig-5-12 fig-pos='H'}\n:::\n:::\n\n\n\n补充量随着繁殖生物量增加而下降背后的理念是，这与某些群体对其他群体的竞争或捕食效应（同类相食）有关。已经提出了各种机制，包括成鱼捕食幼鱼、疾病在密度依赖性传播、繁殖成鱼对彼此产卵场的损害（主要发生在像鲑鱼这样的鱼类生活的河流中），以及最终密度依赖性生长与大小依赖性捕食相结合。这些机制中的每一种都可以导致对 Ricker 曲线参数的不同解释。\n\n再次，方程是否应该被解释为对可观察世界的说明，而不仅仅是平均补充量的便利经验描述，这一点变得重要。此外，尽管参数当然可以被赋予现实世界的解释，但方程仍然倾向于过于简单，最好被视为对事件的说明，而不是经验描述（Punt and Cope, 2019）。\n\n### Deriso 的通用模型\n\nDeriso (1980) 提出了一个通用方程，其中 Beverton–Holt 和 Ricker 种群补充曲线是它的特例。Schnute (1985) 重新构建了 Deriso 的方程，产生了一个更加灵活的版本，具有更高的灵活性：\n\n$$\nR_y = \\alpha S_y(1-\\beta \\gamma S_y)^{1/\\gamma}\n$$ {#eq-5_18}\n\n在这个 Schnute (1985) 通用情况下有三个参数 $\\alpha$ 、 $\\beta$ 和 $\\gamma$，前两个参数应始终为正，但 $\\gamma$ 可以为正或负。通过修改 $\\gamma$ 值，会出现不同的特例 [@fig-5-13] ：\n\n$$\n\\begin{split}\n\\gamma = -\\infty \\quad &R_y =\\alpha B_y \\\\\n\\gamma = -1 \\quad &R_y = \\alpha B_y/(1+\\beta B_y) \\\\\n\\gamma \\to 0 \\quad &R_y = \\alpha B_y e^{-\\beta B_y} \\\\\n\\gamma = 1 \\quad &R_y = \\alpha B_y (1-\\beta B_y)\n\\end{split}\n$$ {#eq-5_19}\n\n第三个情况中的箭头表示“趋近”，例如 $\\gamma$ 趋近于零。第一个情况是密度无关的补充率常数，也可以通过设置 $\\beta= 0$ 得到。接下来的三种情况分别对应于 Beverton–Holt (1957)、Ricker (1954, 1958) 和 Schaefer (1954) 的标准种群-补充量关系，这是一种逻辑斯蒂曲线的形式。当然，在每种情况下都需要小心选择 $\\alpha$ 和 $\\beta$ 的适当值。\n\nDeriso–Schnute 模型存在一些数学上不稳定的特性，如果我们设 $\\gamma = 0$ ，这一点应该很清楚。这会导致数学上的奇点（除以零）。参数限制应该始终为 $\\gamma \\to 0$ ，无论是从负方向还是正方向。使用这个方程，有许多参数组合会产生不合理的种群补充关系。这个方程的主要价值在于展示不同曲线之间的关系，虽然人们不会在拟合模型中使用 Deriso-Schnute 模型，但它可能在模拟模型中很有用。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # plot of three special cases from Deriso-Schnute curve  Fig. 5.13  \nderiso <- function(p,B) return(p[1] * B *(1 - p[2]*p[3]*B)^(1/p[3]))  \nB <- 1:10000  \nplot1(B,deriso(c(10,0.001,-1),B),lwd=2,  \n      xlab=\"Spawning Biomass\",ylab=\"Recruitment\")       # BH  \nlines(B,deriso(c(10,0.0004,0.25),B),lwd=2,col=2,lty=2)  # DS  \nlines(B,deriso(c(10,0.0004,1e-06),B),lwd=2,col=3,lty=3) # Ricker  \nlines(B,deriso(c(10,0.0004,0.5),B),lwd=2,col=1,lty=3)   # odd line  \nlegend(x=7000,y=8500,legend=c(\"BH\",\"DS\",\"Ricker\",\"odd line\"),  \n       col=c(1,2,3,1),lty=c(1,2,3,3),bty=\"n\",lwd=3)  \n```\n\n::: {.cell-output-display}\n![Beverton-Holt (BH)、Ricker 和 Deriso-Schnute (DS) 种群-补充量曲线的比较，\n这些曲线在 Deriso-Schnute 通用方程 Equ (5.19) 中实现。\n对于 DS 曲线， $\\gamma = 0.5$ 导致不切实际的结果（奇线）。](05-staticModel_files/figure-pdf/fig-5-13-1.pdf){#fig-5-13 fig-pos='H'}\n:::\n:::\n\n\n\n### 重新参数化的 Beverton-Holt 方程\n\n在《模型参数估计》( @sec-paraestimat) 章中，对 tigers 数据集中的虎虾 Beverton-Holt 种群-补充量曲线的参数进行了估计。相对丰度的估计可以等同于短命对虾种类的补充量水平，但对于使用年龄结构模型的寿命更长的物种，估计此类参数将相对抽象。Francis（1992）对更复杂的种群评估模型做出了重要发展，他重新参数化了 Beverton-Holt 种群-补充量关系，以曲线的初始陡峭程度 $h$ 和初始补充量 $R_0$ 来表示，其中 $R_0$ 是从未捕捞或原始繁殖生物量 $B_0$ 推导出来的。他首先将这些想法应用于胸棘鲷（*Haplostethus atlanticus*）的年龄结构剩余生产模型，该模型具有捕捞数据、来自调查的相对丰度指数以及与年龄相关生长和重量的生物学数据。使用这些数据，他能够以更合理的方式拟合模型，并利用他对补充量的更有意义的参数化方法。\n\nFrancis（1992）将陡峭程度，记作 $h$，定义为当成熟生物量减少到未捕捞水平的 20%时，种群产生的确定性补充量。他开始描述时使用了：\n\n$$\nR_0 = \\dfrac{A_0}{\\alpha + \\beta A_0}\n$$ {#eq-5_20}\n\n因此，通过定义陡峭度， $h = 0.2 B_0$，我们得到：\n\n$$\nh R_0 =\\dfrac{0.2 A_0}{\\alpha + \\beta 0.2 A_0}\n$$ {#eq-5_21}\n\n其中 $\\alpha$ 和 $\\beta$ 是 Beverton-Holt 参数， $A_0$ 是未受捕捞种群中稳定年龄分布的单位补充量总繁殖生物量。”单位补充“ 部分对年龄结构模型很重要，因为它允许我们独立于 Beverton-Holt 方程 [@eq-5_15] 来确定 $R_0$ 和 $B_0$ 之间的关系。稳定的年龄分布是由恒定的补充量水平 $R_0$ 在恒定的自然死亡率（ $M$ ）产生的 ，导致年龄组数量呈现标准指数下降。如果自然死亡率较低，则可能需要增加一个年龄组。这个稳定年龄分布可以定义为：\n\n$$\n\\begin{split}\nn_{0,a} = \\left \\{ \\begin{matrix}\nR_0 e^{-Ma} \\quad  & a < t_{max} \\\\\nR_0 e^{-Mt_{max}}/(1-e^{-M})  \\quad &a = t_{max}  \\end{matrix} \\right.\n\\end{split}\n$$ {#eq-5_22}\n\n其中 $n_{0,a}$ 表示年龄 $a$ 的单位补充量未被捕捞的数量，而 $t_{max}$ 表示模型中模拟的最大年龄。 $t_{max}$ 作为一组附加年龄组，因此需要除以 $(1-e^{-M})$ 以提供指数序列的和。生物量 $A_0$ 将是具有恒定补充水平为 1 时产生的种群生物量。因此，对于生物量 $A_0$，在稳定的年龄分布下，产生的补充水平将是 $R_0 = 1$（反之亦然）。\n\n$$\nA_0 = \\left(\\sum_m n_{0,a} w_a \\right)\n$$ {#eq-5_23}\n\n其中 $m$ 表示成熟年龄， $n_{0,a}$ 表示年龄 $a$ 的单位补充量未被捕捞的数量， $a$ 表示年龄， $w_a$ 表示年龄 $a$ 的单位鱼体重量。人们还可以将部分自然死亡率纳入此方程，使其在一年中的某个时间点与补充量相等。 $A_0$ 作为缩放因子，因为在任何恒定的补充量水平下，未受干扰的种群都会出现稳定的年龄分布。 $A_0$ 的幅度将根据估计的初始生物量 $B_0$ 进行缩放，但其值相对于维持稳定年龄分布所需的恒定补充量 $R_0$ 将保持不变。在实践中，人们会根据生物学信息推导出 $A_0$，并在种群评估模型中估计 $R_0$。\n\n$$\nB_0 = R_0 \\left(\\sum_m n_{0,a} w_a \\right) = (R_0 A_0)\n$$ {#eq-5_24}\n\nFrancis（1992）随后也使用了他对补充量陡峭程度的定义来重新参数化Beverton-Holt 参数 $a$ 、 $b$ 、 $\\alpha$ 和 $\\beta$ （见本章附录）：\n\n$$\na = \\dfrac{4hR_0}{(5h-1)} \\quad b = \\dfrac{B_0(1-h)}{(5h-1)} \n$$ {#eq-5_25}\n\n将这些公式代入 @eq-5_16 中，得到：\n\n$$\nR_y = \\dfrac{\\frac{4hR_0}{(5h-1)} B_y}{\\frac{B_0(1-h)}{(5h-1)} + B_y}\n$$ {#eq-5_26}\n\n将上层的 $(5h-1)$ 移到下层：\n\n$$\nR_y = \\dfrac{4hR_0 B_y}{\\frac{(5h-1) B_0 (1-h)}{(5h-1)} +(5h-1)B_y}\n$$ {#eq-5_27}\n\n然后，在可能的情况下消去 $(5h-1)$，可以将 Beverton-Holt 重新定义为陡峭度 $h$ 、 $B_0$ 和 $R_0$ ，这些都有更明确的解释，并且使用 @eq-5_25 或 @eq-5_28 将更容易在评估模型中进行估计：\n\n$$\nR_y = \\dfrac{4hR_0B_y}{B_0(1-h) + B_y(5h-1)} \n$$ {#eq-5_28}\n\n### 重新参数化的 Ricker 方程\n\n类似地，Ricker 种群补充方程可以重新参数化为陡峭度 $h$、 $B_0$ 和 $R_0$ ：\n\n$$\nR_y = \\dfrac{R_0 B_y}{B_0} \\exp \\left(h \\left(1-\\frac{B_y}{B_0} \\right) \\right)\n$$ {#eq-5_29}\n\n@eq-5_25 和 @eq-5_28 现在都是用于种群评估和试图包含补充量的模拟模型中更常用的参数化方法。\n\n## 选择性\n\n### 引言\n\n在种群评估模型（及模拟）中使用的另一类静态模型与渔具对特定物种的选择性有关。其核心思想是，如果一个被开发物种的种群在某个区域存在，那么如果使用特定的渔具（如拖网、丹麦围网、刺网、龙虾笼等），渔具的构造及其使用方式将影响在遇到渔具时，哪些可用的种群成员会对其变得脆弱。在年龄结构评估模型中，选择性的概念因可用性的概念而变得复杂。例如，如果某个物种的主要捕捞场所在水深超过 250 米的区域，而较浅水域中主要只有较小的幼体存在，那么如果仅使用浅水域的数据来估计渔具的选择性，其结果很可能与使用深水域数据得到的估计结果不同。实际上，在评估模型中估计的选择性曲线应该被视为选择性/可用性曲线。\n\n选择选择性曲线的形状是一个重要的决策。某些捕捞工具通常用特定的方程来描述其选择性。因此，拖网工具的选择性通常用逻辑斯蒂方程来描述，而长线工具（使用钩子）通常用拱形选择性函数来描述。\n\n只有在有捕捞年龄或大小组成数据的情况下，才能在资源评估模型中拟合选择性模型。正如我们在模型参数估计章节中所看到的，通常会用多项式似然来拟合这种组成数据。在资源评估模型中，通常会根据预期年龄数量来模拟种群动态，这会隐含某些大小数量。因此，在尝试生成预测的捕捞组成数据（无论是年龄还是大小）时，需要将可用的年龄或大小数量乘以预测的选择性。因此，在拟合过程中，组成数据会帮助估计选择性参数。\n\n本节中我们仅将说明其他选择性的方程式，并展示它们的不同特性。\n\n### 逻辑斯蒂选择\n\n描述不同渔具选择性特征的不同方程式有很多，但其中一种极其常见的是标准逻辑斯蒂曲线或 S 形曲线，这通常是拖网渔具选择性的典型特征。它意味着随着年龄或个体大小的增加，渔具的易受害性会逐渐增加，直到 100% 的个体在遇到渔具时都变得易受害（这种逐渐增加到 100% 的过程与成熟过程相同）。通常使用两个方程式，第一个由 **MQMF** 函数 `logist()` 描述：\n\n$$\ns_a = \\dfrac{1}{1 + e^{-\\log(19)(a-a_{50})/\\delta}}\n$$ {#eq-5_30}\n\n其中 $S_a$ 是年龄 $a$ 的选择性（比例）， $a_{50}$ 是选择性达到 50% 时的年龄， $\\delta$ 是曲线的斜率，定义为从选择性 50%到选择性 95%之间的年数。当我们谈论年龄时，同样也可以谈论大小。 $\\delta$ 的上限为 95%（实际上 $\\delta$ 是 $L95-L50$ ）。另一种对数曲线，我们在《简单种群模型》[@sec-simplemodel] 一章的 “YPR 中的选择性” [@sec-ypr_selectivity] 节中已经见过，也被用来描述年龄成熟度，它在函数 `mature()` 中定义：\n\n$$\ns_a = \\dfrac{1}{1+(e^{(\\alpha + \\beta a)})^{-1}} = \\dfrac{e^{(\\alpha + \\beta a)}}{1+ e^{(\\alpha + \\beta a)}}\n$$ {#eq-5_31}\n\n其中 $\\alpha$ 和 $\\beta$ 是逻辑斯蒂参数， $- \\alpha/\\beta$ 是0.5 选择性（即 50%）的年龄。四分位距（字面意思是 25%分位数到 75%分位数）定义为 $IQ = 2\\log(3)/\\beta$ （有关此函数的实现，请参阅 **MQMF** 函数 `mature()`）。通常，在年龄结构模型中，需要长度或年龄组成数据，以便可以直接估计渔具选择性和渔业可利用性。在进行单位补充量渔获量计算时，通常包含选择性的原因是确定开始应用捕捞死亡率的最佳年龄。出于这个原因，通常使用所谓的刀刃选择性，它本质上识别出以下没有选择性的特定年龄，以及以上 100% 选择性的年龄。这在 **MQMF** 函数 `logist()` 中实现；尽管刀刃选择性不再倾向于用于完整的年龄结构种群评估模型，但它仍然用于延迟差分模型（Schnute，1985；Hilborn 和 Walters，1992）。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #Selectivity curves from logist and mature functions  See Fig 5.14\nages <- seq(0,50,1);   in50 <- 25.0  \nsel1 <- logist(in50,12,ages)         #-3.65/0.146=L50=25.0  \nsel2 <- mature(-3.650425,0.146017,sizeage=ages)  \nsel3 <- mature(-6,0.2,ages)  \nsel4 <- logist(22.0,14,ages,knifeedge = TRUE)  \nplot1(ages,sel1,xlab=\"Age Years\",ylab=\"Selectivity\",cex=0.75,lwd=2)  \nlines(ages,sel2,col=2,lwd=2,lty=2)  \nlines(ages,sel3,col=3,lwd=2,lty=3)  \nlines(ages,sel4,col=4,lwd=2,lty=4)  \nabline(v=in50,col=1,lty=2); abline(h=0.5,col=1,lty=2)  \nlegend(\"topleft\",c(\"25_eq5.30\",\"25_eq5.31\",\"30_eq5.31\",\"22_eq5.30N\"),  \n       col=c(1,2,3,4),lwd=3,cex=1.1,bty=\"n\",lty=c(1:4))  \n```\n\n::: {.cell-output-display}\n![ logist() 和 mature() 函数的逻辑 S 形曲线示例。虚线红色和实线黑色曲线具有相同的 L50，但梯度不同。点线绿色展示了改变 `mature()` 函数的 b 参数的效果，而交叉线蓝色曲线展示了刀刃式选择。图例显示了 L50 和使用的方程。](05-staticModel_files/figure-pdf/fig-5-14-1.pdf){#fig-5-14 fig-pos='H'}\n:::\n:::\n\n\n\n### 球面选择性\n\n一种上升至峰值的选择性模式、可能存在平台段，然后下降的模式被称为穹顶形，这是网具（如围网）和钩具（如延绳钓）等渔具的典型特征。由于包含如此多的组成部分，选择性曲线往往更为复杂，因为上升段、平台段和下降段都需要连接在一起。现代拟合此类模型的方法倾向于使用自动微分软件，如 AD-Model Builder 或相关软件（Bull 等，2012；Fournier 等，2012；Kristensen 等，2016）。这意味着评估模型中的组件模型需要可微分，以便穹顶形选择性曲线的三个组成部分之间的连接需要连续（Methot 和 Wetzell，2013；Hurtado-Ferro 等，2014）。此类方程至少包含五个组成部分：上升段（*asc*）、选择性等于 1.0 的平台段、下降段（*des*）、以及连接这三个主要部分之间的两个连接函数、 $J_1$ 和 $J_2$， @eq-5_32 ：\n\n$$\ns_L = asc(1-J_{1,L}) +J_{1,L}((1-J_{2,L})+J_{2,L} dsc)\n$$ {#eq-5_32}\n\n其中 $S_L$ 表示长度 $L$ 的选择性。各种分量函数定义如下：\n\n$$\n\\begin{split}\nasc &= 1-(1-\\lambda_5) \\left(\\dfrac{1-\\exp \\left((m_L - \\lambda_1)^2/\\lambda_3 \\right)}{1-\\exp \\left((m_{min}-\\lambda_1)^2/\\lambda_3 \\right)} \\right) \\\\\ndsc &= 1- \\exp\\left(-\\left(m_L- \\lambda_2)^2/\\lambda_4 \\right) \\right) \\\\\nJ_{1,L} &=1/(1+ \\exp(-(m_L-\\lambda_1)/(1 +|m_L+\\lambda_1|)))\\\\\nJ_{2,L} &= 1/(1+ \\exp(-(m_L-\\lambda_2)/(1+|m_L + \\lambda_2|)))\n\\end{split}\n$$ {#eq-5_33}\n\n其中 $m_L$ 是长度组 $L$ 的平均长度， $m_{min}$ 是最小长度组的平均长度， $\\lambda_1$ 是选择性达到 1.0 的个体大小， $\\lambda_2$ 是选择性从 1.0 开始下降的个体大小（如果 $\\lambda_1$ 和 $\\lambda_2$ 相等则没有平台期）， $\\lambda_3$ 影响上升段（*asc*）的斜率， $\\lambda_4$ 影响下降段（*dsc*）的斜率， $\\lambda_5$ 是 $m_{min}$ 处选择性的对数， $\\lambda_6$ 是 $m_{max}$ 选择性的对数， @fig-5-15 。\n\n因此，需要 $\\lambda_1$ 到 $\\lambda_6$ 六个参数以及所使用的长度组的平均长度来定义这种穹顶选择性曲线。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n #Examples of domed-shaped selectivity curves from domed. Fig.5.15  \nL <- seq(1,30,1)  \np <- c(10,11,16,33,-5,-2)  \nplot1(L,domed(p,L),type=\"l\",lwd=2,ylab=\"Selectivity\",xlab=\"Age Years\")  \np1 <- c(8,12,16,33,-5,-1)  \nlines(L,domed(p1,L),lwd=2,col=2,lty=2)  \np2 <- c(9,10,16,33,-5,-4)  \nlines(L,domed(p2,L),lwd=2,col=4,lty=4)  \n```\n\n::: {.cell-output-display}\n![由函数 domed() 产生的三个拱形选择性曲线示例，改变了达到选择性 1.0 的初始年龄（10、8、9），以及停止时的年龄（11、12、10），以及最终年龄组的选择性。](05-staticModel_files/figure-pdf/fig-5-15-1.pdf){#fig-5-15 fig-pos='H'}\n:::\n:::\n\n\n\n## 静态模型的结论性评述\n\n比我们已考虑的剩余产量模型更复杂的种群评估模型，大多是混合了群体进展的动态模型和本章所说明的静态模型集合。因此，了解生长、成熟、选择性和补充模型对于理解更高级模型的结构至关重要。有时人们会在评估模型之外估计它们的参数，但通常估计会是拟合整个种群评估模型的一部分。一次性拟合所有独立模型组件的优势在于，组件之间的任何交互作用都可以自动考虑。\n\n本章为一系列静态模型提供了入门基础。目标是当你遇到其他模型时，能够像我们这里使用的方法一样使用和拟合它们。每种这样的模型都有其自身的假设。只要你知道这些假设，你应该能够为你在建模中选择使用哪种静态模型做出决策并提供辩护。\n\n## 附录：Fabens 变换的推导\n\nFabens（1965）将 von Bertalanffy 生长曲线进行转换，使其与标记计划提供的数据相匹配（标记时的长度和日期，以及重捕时的长度和日期）。von Bertalanffy 曲线的年龄-长度版本为：\n\n$$\n\\hat {L_t} = L_{\\infty} \\left(1- e^{(-K(t-t_0))} \\right) +N(0, \\sigma)\n$$ {#eq-5_34}\n\n在标记的背景下，它在给定时间增量（ $\\Delta t$ ）后的长度定义为：\n\n$$\nL_{t +\\Delta t} = L_{\\infty} - L_{\\infty} e^{-K((t + \\Delta t)-t_0)}\n$$ {#eq-5_35}\n\n在指数项中，可以提取 $\\Delta t$ 的贡献：\n\n$$\nL_{t+\\Delta t} = L_{\\infty} - L_{\\infty} e^{-K(t-t_0)} e^{-K \\Delta t}\n$$ {#eq-5_36}\n\n现在，在 $\\Delta t$ 期间预期发生的生长增量 $\\Delta L$ 可以定义为 $L_{t +\\Delta t}$ 减去 $L_t$：\n\n$$\n\\Delta L = (L_{t + \\Delta t}-L_t) = \\\\\n\\left(L_{\\infty}-L_{\\infty}e^{-K(t-t_0)}e^{-K \\Delta t} \\right) - \\left(L_{\\infty} - L_{\\infty}e^{(-K((t-t_0))} \\right)\n$$ {#eq-5_37}\n\n我们可以去掉括号，这将使第二项中的否定变为加号，然后重新排列分离的项。\n\n$$\n\\Delta L = L_{\\infty}-L_{\\infty}e^{-K(t-t_0)}e^{-K \\Delta t}  - L_{\\infty} + L_{\\infty}e^{(-K((t-t_0))}\n$$ {#eq-5_38}\n\n这两个孤立的 $L_{\\infty}$ 项可以消去以提高证明的清晰度，但它们稍后会重新出现。此外，我们还可以重新排列剩下的两个指数项：\n\n$$\n\\Delta L = L_{\\infty} e^{(-K(t-t_0))} -L_{\\infty} e^{-K(t-t_0)}e^{-K \\Delta t}\n$$ {#eq-5_39}\n\n重新排列使得可以提出出 $L_{\\infty}e^{(-K(t -t_0))}$ 项来简化整个方程：\n\n$$\n\\Delta L = L_{\\infty} e^{(-K(t-t_0))}\\left(1-e^{-K \\Delta t}\\right)\n$$ {#eq-5_40}\n\n现在我们可以将 $\\Delta t$ 项移至左边，并返回 $L_{\\infty} - L_{\\infty}$ 项\n\n$$\n\\frac{\\Delta L}{(1-e^{-K \\Delta t})} = L_{\\infty} - L_{\\infty} + L_{\\infty} e^{(-K(t-t_0))}\n$$ {#eq-5_41}\n\n如果我们添加一些括号，将加号变为减号，我们最终就能认识到哪些项的组合等于 $L_t$ ：\n\n$$\n\\dfrac{\\Delta \\hat L}{(1-e^{-K \\Delta t})} = L_{\\infty}-\\left(L_{\\infty}-L_{\\infty}e^{(-K(t-t_0))} \\right)\n= (L_{\\infty}-L_t)$$ {#eq-5_42}\n\n通过将 $\\Delta t$ 项移至右侧，得到经典的 Fabens 生长增量方程：\n\n$$\n\\Delta L = (L_{\\infty}-L_t)\\left(1-e^{-K \\Delta t} \\right)\n$$ {#eq-5_43}\n\n需要注意的是，这种转换也会转换长度-年龄方程中的正态随机残差，而这些残差当然是在参数估计时使用的。这意味着，尽管这些参数具有相同的名称，但它们并不严格可比。\n\n## 附录：Beverton-Holt 模型的重新参数化\n\nFrancis（1992）以更具有生物学意义的陡峭程度（ $h$ ）、 初始成熟生物量（ $B_0$）和 初始补充量（ $R_0$ ）等术语来定义 Beverton-Holt 参数。与其使用\n\n$$\nR_y = \\dfrac{B_{y-1}}{\\alpha + \\beta B_{y-1}} \n$$ {#eq-5_44}\n\n不如使用另外一种公式，尽管最后还是要回到使用关系 $\\alpha = b/a$ 和 $\\beta = 1/a$ 。\n\n因此，我们将使用：\n\n$$\nR_y = \\dfrac{a B_y}{b+ B_y}\n$$ {#eq-5_45}\n\n其中 $R_y$ 是年 $y$ 的补充量， $B_y$ 是 $y$ 年繁殖资源量， $a$ 和 $b$ 是 Beverton-Holt 参数。在未受捕捞的平衡状态下，我们可以将方程表示为：\n\n$$\nR_0 = \\dfrac{a B_0}{b + B_0}\n$$ {#eq-5_46}\n\n陡度（ $h$ ）定义为初始生物量的20% 时获得的补充量：\n\n$$\nh R_0 = \\dfrac{0.2 a B_0}{b + 0.2 B_0}\n$$ {#eq-5_47}\n\n如果 $R_0$ 的平衡方程代入这个方程，我们将得到：\n\n$$\nh \\dfrac{a B_0}{b + B_0}= \\dfrac{0.2 a B_0}{b + 0.2 B_0}\n$$ {#eq-5_48}\n\n因此：\n\n$$\nh = \\dfrac{(0.2a B_0)(b+B_0)}{(b+0.2B_0)(aB_0)}= \\dfrac{0.2(b + B_0)}{b + 0.2 B_0}\n$$ {#eq-5_49}\n\n通过乘法得到 ：\n\n$$\nh b + 0.2hB_0 = 0.2b + 0.2 B_0\n$$ {#eq-5_50}\n\n通过交换项以将 $b$ 和 $B_0$ 分开，然后乘以5 以消除 0.2：\n\n$$\n5hb -b = B_0- h B_0\n$$ {#eq-5_51}\n\n简化后得到：\n\n$$\nb(5h-1) = B_0 (1-h)\n$$ {#eq-5_52}\n\n因此 $b$ 可重新参数为：\n\n$$\nb = \\dfrac{B_0(1-h)}{(5h-1)}\n$$ {#eq-5_53}\n\n该版本的 $b$ 可以用于原始方程，并重新排列以对 $a$ 参数做类似处理：\n\n$$\nR_0 = \\dfrac{a B_0}{\\frac{B_0(1-h)}{(5h-1)} +B_0}\n$$ {#eq-5_54}\n\n转换为：\n\n$$\nR_0 \\dfrac{B_0(1-h)}{(5h-1)} +R_0 B_0 = a B_0\n$$ {#eq-5_55}\n\n除以 $B_0$ ，然后将等号左侧的第二项 $R_0$ 乘以 $5h-1$，简化为：\n\n$$\n\\dfrac{R_0 -R_0h +5hR_0-R_0}{5h-1}= \\dfrac{4hR_0}{5h-1} = a\n$$ {#eq-5_56}\n\n记住 $\\alpha = b/a$ 和 $\\beta = 1/a$ ，所以就可以完成了：\n\n$$\n\\alpha =b \\times 1/a = \\dfrac{B_0(1-h)}{(5h-1)} \\times \\dfrac{5h-1}{4hR_0} = \\dfrac{B_0(1-h)}{4hR_0}\n$$ {#eq-5_57}\n\n以及：\n\n$$\nb = 1/a = \\dfrac{5h-1}{4hR_0}\n$$ {#eq-5_58}\n\n如 Francis (1992) 所定义。这重新定义了 Beverton-Holt 模型参数，以 $h$、 $B_0$ 和 $R_0$ 表示。需要确定 $B_0$ 和 $R_0$ 之间的关系，但我们不能使用平衡方程来计算，因此我们假设未受捕捞的种群处于具有稳定年龄分布的平衡状态。从稳定年龄分布中每单位亲体产生的成熟生物量 ( $A_0$ ) 因此定义了 $B_0$ 和 $R_0$ 之间所需的关系。\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}